### ISSUE TITLE
Support any Sentry instance via DSN

### ISSUE THREAD

**Issue by florianm** [getodk/central#106]
As an ODK Central maintainer, I'd like to use my self-hosted Sentry instance.

[lib/util/sentry](https://github.com/opendatakit/central-backend/blob/268ec9e380d3e16b1c52e59599dadef5c0784d36/lib/util/sentry.js#L17) builds the DSN using project ID and client key, but hard-codes the sentry domain to sentry.io.

Since Sentry provides the DSN in one bit, it would be actually easier for maintainers to copy-paste that DSN into a new config setting `default.external.sentry.dsn` than to extract `project` and `key`.

This would require changes:

1. [config](https://github.com/opendatakit/central-backend/blob/master/config/default.json#L24)
```
"sentry": {"dsn":"DEFAULT_DSN"}
```

2. [Sentry init](https://github.com/opendatakit/central-backend/blob/268ec9e380d3e16b1c52e59599dadef5c0784d36/lib/util/sentry.js#L17)

```
 Sentry.init({
    dsn: `{config.dsn}`,
...
```

3. [Docs](https://github.com/opendatakit/docs/blob/master/odk1-src/central-install-digital-ocean.rst#disabling-or-customizing-sentry)

4. Tests

**Comment by issa-tseng** [comment]
i think this proposal sounds reasonable but it's off the beaten path for the majority of users so my time is needed elsewhere. i would welcome pull requests for this.

any proposed solution can't break back compat with existing configuration, though.

**Comment by florianm** [comment]
How about if Sentry init would check first for older config (`project` and `key`), then for newer `dsn`? (Cleaner in future and easier for users to set)

Or would you prefer to add `instance` to the Sentry config? (easier to migrate but mildly more tedious for users to set)

**Comment by issa-tseng** [comment]
the first option sounds fine to me.

**Comment by RemiDesgrange** [comment]
You can override default via env var. Like SENTRY_DSN etc... see the [sentry doc](https://docs.sentry.io/error-reporting/configuration/?platform=javascript)

**Comment by florianm** [comment]
Just came up in a ODK TAB discussion - the built-in Sentry reporting is extremely valuable for GetODK to track usage, adoption, get a feel of when a feature is safe to deprecate (when not used any more), in addition to bug reports.

I'd like to revise my initial idea to say "allow one *additional* Sentry logger".

**Comment by florianm** [comment]
I'm closing this, as server logs (eg. `docker-compose logs -f nginx service`) are good enough for troubleshooting, and we want to keep sending insight to the ODK core team via the configured main Sentry DSN.
