### ISSUE TITLE
Link to the App User's QR code

### ISSUE THREAD

**Issue by OdiljonQurbon** [getodk/central#123]
It would be nice to have a link to the QR code in Response when [Creating a new App User via API](https://odkcentral.docs.apiary.io/#reference/accounts-and-users/app-users/creating-a-new-app-user). Moreover it would be very useful if admins of the server could request the QR code for each App User via API.
Thanks.

**Comment by issa-tseng** [comment]
thanks for this feedback! we've received something similar to it before. how do you intend to distribute the link/image once you have it?

**Comment by OdiljonQurbon** [comment]
Image of the QR could be published in password protected website.

**Comment by issa-tseng** [comment]
would you want, like, some information included in the image along with the QR code? or would it be better if it was just the code?

**Comment by OdiljonQurbon** [comment]
I think just QR code would be enough as we get enough data in the response when Creating a new App User.

**Comment by matthew-white** [comment]
Just to link discussions, I thought I'd note that there was a similar request on the ODK forum here: https://forum.getodk.org/t/using-central-api-to-access-collect-qr-code/27071.

**Comment by matthew-white** [comment]
We've been discussing ways to improve the app user QR code and are thinking increasingly that the generation of the QR code should remain on the frontend. One thing we want to do is add the project name and the app user name to the QR code image. However, while that's quite doable on the frontend, it'd be more challenging to do on the backend. With that in mind, I think I'm going to go ahead and close this issue. Thank you for suggesting this, @OdiljonQurbon!
