### ISSUE TITLE
Add support for custom (non 80/443) ports

### ISSUE THREAD

**Issue by yanokwa** [getodk/central#138]
Some folks want to run on custom ports. https://forum.getodk.org/t/odk-central-with-nonstandard-port-number-and-custom-ssl-cannot-retrieve-forms-with-collect/26264

Some reasons to not do this.
- You can setup a reverse proxy on the machine that does this. If you have a fancy firewall, it can do this too.

**Comment by issa-tseng** [comment]
seems fine to put this in `.env` to me.

**Comment by yanokwa** [comment]
Closed by #213.
