### ISSUE TITLE
Link to the QR code for testing Draft form

### ISSUE THREAD

**Issue by OdiljonQurbon** [getodk/central#139]
Similar to the [App User's QR code issue](https://github.com/getodk/central/issues/123) is it possible to get the link to Draft Form testing QR Code image by API call, or include this QR Code into the response when posting a draft form using [Creating a Draft Form](https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/'-draft-form/creating-a-draft-form). 
Thank you for your great work!

**Comment by OdiljonQurbon** [comment]
I thought that 
> When a Draft Form is created, a Draft Token is also created for it, which can be found in Draft Form responses at `draftToken`. [(link)](https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/'-draft-form/creating-a-draft-form)

could be the solution but I don't see draftToken in the response when I post form in R:
Response I get: 
```
Response [https://[server]/v1/projects/[pid]/forms]
  Date: 2020-06-07 14:36
  Status: 200
  Content-Type: application/json; charset=utf-8
  Size: 418 B

**Comment by matthew-white** [comment]
Hi @OdiljonQurbon!

> I don't see draftToken in the response when I post form in R:

I think the Form endpoints don't return a Draft Token, but the Draft Form endpoint does: if you request /v1/projects/[projectId]/forms/[xmlFormId]/draft, the response should contain a Draft Token.

**Comment by OdiljonQurbon** [comment]
Hello @matthew-white !
My first call from R is following:
```R
  pxlsxfile <- PATH_TO_XLSX_FILE
  un <- MYUSERNAME
  pw <- SUPERSECRETPASS
  
  server <- MYSERVER_URL
  pid <- 1

  url <- glue("{server}/v1/projects/{pid}/forms/?ignoreWarnings=false")

  ## POST form in xlsx format to Central
  myxlsxfile <- httr::upload_file(xlsxfile, type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
  httr::POST(url,
            httr::add_headers(
              "X-XlsForm-FormId-Fallback" = 'simple'
            ),
            httr::authenticate(un, pw),
            body = myxlsxfile
  )
```
got the response:
```
Response [https://[server]/v1/projects/1/forms?ignoreWarnings=false]
  Date: 2020-06-07 20:39
  Status: 200
  Content-Type: application/json; charset=utf-8
  Size: 422 B
```

Then I tested below code to `/draft` endpoint as you suggested:
```R
  pxlsxfile <- PATH_TO_XLSX_FILE
  un <- MYUSERNAME
  pw <- SUPERSECRETPASS
  
  server <- MYSERVER_URL
  pid <- 1

  url <- glue("{server}/v1/projects/{pid}/forms/simple/draft?ignoreWarnings=false")

  ## POST form in xlsx format to Central
  myxlsxfile <- httr::upload_file(xlsxfile, type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
  httr::POST(url,
            httr::add_headers(
              "X-XlsForm-FormId-Fallback" = 'simple'
            ),
            httr::authenticate(un, pw),
            body = myxlsxfile
  )
```
```
Response [https://[server]/v1/projects/1/forms/simple/draft?ignoreWarnings=false]
  Date: 2020-06-07 20:41
  Status: 200
  Content-Type: application/json; charset=utf-8
  Size: 16 B
```
As [documentation ](https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/forms/creating-a-new-form) indicates 

> As of Version 0.8, Forms will by default be created in Draft state, ...

So I cannot see any difference in the API call response to above two calls. Maybe I'm doing something wrong but don't know what exactly should I fix.

**Comment by issa-tseng** [comment]
once the form is created you will want to `GET` the `/draft` details, not post to it. then you should find the `draftToken`.

**Comment by OdiljonQurbon** [comment]
Thanks @issa-tseng !
> once the form is created you will want to `GET` the `/draft` details, ...

GET request brings draftToken. But I think using this `draftToken` with ODK Collect is not ready yet, am I right? I still need to use QR code to be able to send submissions.

**Comment by OdiljonQurbon** [comment]
Thanks @issa-tseng ! I'm getting `draftToken` using GET call to the server.

**Comment by OdiljonQurbon** [comment]
Having `draftToken` makes possible to generate QR Code. Thank you.
