### ISSUE TITLE
Message for email uniqueness violation

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#144]
Right now if you try to create a user with an email that is already in use, the following message is shown:

> A resource already exists with email,deleted value(s) of some@email.com,false.

Since this is a message that a user might see, I think it would be nice to show a slightly clearer message. (Not sure whether that's a change that would be better done in Backend or Frontend.)

**Comment by matthew-white** [comment]
Another time when this message is shown is if you try to change a user's email address to the email address of another existing user.

**Comment by dbemke** [comment]
Tested with success!

**Comment by srujner** [comment]
**Tested with success!**
