### ISSUE TITLE
letsencrypt problem after upgrade to 0.9

### ISSUE THREAD

**Issue by dmenne** [getodk/central#151]
After upgrading from 0.8 to 0.9 on a DigitalOcean installation, the nginx-container restarts exactly after 60 seconds. I can reach the login page, but here is "no response" to the request.

Log of nginx-container indicates a problem with letsencrypt. I have followed https://docs.getodk.org/central-upgrade/ including firewall disabling. All other containers run ok.

```
nginx: [emerg] BIO_new_file("/etc/selfsign|letsencrypt|customssl/live/local|your.domain.com/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or
 directory:fopen('/etc/selfsign|letsencrypt|customssl/live/local|your.domain.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)                 
writing a new nginx configuration file..                                                                                                                                    
starting nginx without certbot..                                                                                                                                            
2020/07/27 09:23:49 [emerg] 10#10: BIO_new_file("/etc/selfsign|letsencrypt|customssl/live/local|your.domain.com/fullchain.pem") failed (SSL: error:02001002:system library:f
open:No such file or directory:fopen('/etc/selfsign|letsencrypt|customssl/live/local|your.domain.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such fi
le)                                                                                                                                                                         
nginx: [emerg] BIO_new_file("/etc/selfsign|letsencrypt|customssl/live/local|your.domain.com/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or
 directory:fopen('/etc/selfsign|letsencrypt|customssl/live/local|your.domain.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

**Comment by dmenne** [comment]
git did an overwrite of the .env file without complaining, therefore it reads "your.domain.com" in the error message. Restored previous .env.

**Comment by lognaturel** [comment]
Great to hear it’s working for you now! We’d appreciate it if you could write up issues you experience on the community forum as a support request. First, it greatly increases the visibility of your post. In this case, I’m pretty sure others will have a similar experience and having the question and answer in the forum makes it more readily available to others to learn from. Second, it’s sometimes a bit hard to know what repository the issue belongs in before some troubleshooting. It’s simpler for you to post in one place and then we can all work to triage together as we identify the action to take.

Really appreciate all the clear feedback you’ve been giving us! 😊 Hopefully this information makes it even easier to feed your findings back into the community so everyone benefits.
