### ISSUE TITLE
Version 0.9: Enketo reports "invalid date" for a calculated date working in Collect

### ISSUE THREAD

**Issue by dmenne** [getodk/central#152]
I have a text field which is filled in calculation by: ` format-date-time(once(now()),   '%H:%M:%S`

This works fine in ODK Collect, giving date in German Format ( 20.07.2020).

In Enketo Preview (version as of today), and "invalid date" is display - other fields are ok at first sight.

**Comment by lognaturel** [comment]
Thanks! While we now package Enketo with Central, it’s still being developed as a separate project. As I wrote a bit about at https://github.com/getodk/central/issues/151#issuecomment-664481338, sharing issues through the forum will take the triage burden off of you so you can focus on the problem you’re experiencing and its impact on your work.
