### ISSUE TITLE
Update projects table for Data Collectors

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#154]
There are a couple of updates to the projects table that we could consider for Data Collectors:

* @lognaturel [suggested](https://github.com/getodk/central-frontend/pull/354#pullrequestreview-458914452) that we may want to hide the "Latest Submission" column. We already hide the Submissions column of the forms table from Data Collectors (discussed [here](https://github.com/getodk/central-frontend/pull/354#discussion_r463193926)).
* In the forms table, we hide forms without a published version from Data Collectors. However, that means that if a project has a form without a published version, the value of the Forms column of the projects table will be greater than the number of rows of the forms table.

These updates would require changes to Frontend, and they may also require changes to Backend.

**Comment by issa-tseng** [comment]
i don't have a huge issue with the second bullet i feel like. maybe someday we can improve that but it doesn't feel like it matters. heck, i don't even know if form count is really all that useful on its own anyway.

**Comment by matthew-white** [comment]
We're discussing making other changes to the project list and form list as part of v1.5, so I'll go ahead and close this issue. About the second bullet point, I'll note that we're planning to show each project's forms within the project list, so there shouldn't be an issue keeping any form count in sync with the list of forms that are visible to the user.
