### ISSUE TITLE
How to visualize data using Central?

### ISSUE THREAD

**Issue by mbile** [getodk/central#158]
Hello everyone,

I thank anyone who contributed to this great project. Is there a way to visualize the data collected on Central like Aggregate?

**Comment by lognaturel** [comment]
We're glad you're enjoying ODK!

We don't currently have plans to add visualization capabilities to Central. There are great tools for analysis that exist already so our focus is on making it easy to get data into those from Central. Have you explored connecting to Central from tools like Excel or R? Documentation is [here](https://docs.getodk.org/central-submissions/#connecting-to-submission-data-over-odata).

In general, please use [the community forum](https://forum.getodk.org/) for discussion. This allows for more members of the community to participate and lets developers triage issues as appropriate.
