### ISSUE TITLE
ODK Central Build Error (Self Hosting)

### ISSUE THREAD

**Issue by AnthonyAnkrah** [getodk/central#164]
I originally attempted to get ODK Central running on Windows 10 1903 build 18362.1016 with an instance of Docker desktop 2.3.0.4. After executing `docker-compose build` I got

`Service 'nginx' failed to build: The command '/bin/sh -c files/prebuild/write-version.sh' re turned a non-zero code: 127`

I was directed by **Ronald_Munjoma** on [ODK Forum](https://forum.getodk.org/t/odk-central-build-error/29523) to get WSL installed and led me to some guide articles to help with that.
Currently, I am running Windows 10 2004 build 19041.450 (WSL 2 enabled and set as default) with `Docker version 19.03.12, build 48a66213fe` and I still run into the same issue when I attempt to run `docker-compose build`.

Any ideas anybody? Would be awesome to have @yanokwa or any of the contributors help me out with this.
**P.S.** Just in case you missed it, I'm not trying to run this on DigitalOcean. I'm trying to get it running as a self-hosted instance on a Windows 10 device. Thanks.

**Comment by yanokwa** [comment]
Hi @AnthonyAnkrah, support questions should go to the forum. Let's continue the discussion at https://forum.getodk.org/t/odk-central-build-error/29523.
