### ISSUE TITLE
ODK Central v1.1 release

### ISSUE THREAD

**Issue by lognaturel** [getodk/central#169]
This release focuses on giving users more control over what they see in the submission preview table, speeding up load time, and tying up other loose ends.

Please take a look at the details in [this document](https://docs.google.com/document/d/1YcB8orVb6EjgjoXj_1h6v0YHzkwlT3etoRdNl_TKDA4/edit#heading=h.26jkdbfha262). Comments and feedback may be left there, or here.

**Comment by matthew-white** [comment]
v1.1 is now released! 🚀
