### ISSUE TITLE
Get labels and hints from API call form schema

### ISSUE THREAD

**Issue by mtyszler** [getodk/central#172]
Right now a call to form schema via de Central API (as documented at https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/'-individual-form/getting-form-schema-fields) returns `name`, `path`, `type` and `binary`.

It would be extremely useful if the same call would also return `label` and `hint`, in different languages if this is also present.

There is now a workaround possible using the XML (https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/'-individual-form/retrieving-form-xml), but this requires additional parsing and search

See: https://forum.getodk.org/t/include-form-field-labels-and-hints-in-form-schema/27737

See: https://github.com/ropensci/ruODK/issues/77

**Comment by mtyszler** [comment]
@yanokwa . See the new feature added at ruODK (https://github.com/ropensci/ruODK/pull/98)

I'll leave it up to you to decide on whether to close this or not.

**Comment by matthew-white** [comment]
Hi @mtyszler! I'll go ahead and close this issue: if anyone has additional need for an API endpoint, they can head to the feature request on the forum. It's very awesome to see this functionality in ruODK! 🚀
