### ISSUE TITLE
Latitude and longitude are flipped in PowerBI display

### ISSUE THREAD

**Issue by yanokwa** [getodk/central#173]
San Diego is 32,-117 (lat, lon).

Collect's XML: "lat, lon, alt, acc"
`<crop_location>32.737815856933594 -117.1473159790039 0.0 1.0</crop_location>`

Central UI: "lon, lat, alt"
`-117.1473160 32.7378159 0.0`

Shows up in PowerBI as "SRID=4326; POINT (lon, lat, alt)"
`SRID=4326;POINT (-117.14731597900391 32.737815856933594 0)`

When the PowerBI location is mapped (by dragging the field into the location slot of the visualizations column), it definitely looks like lat and lon are flipped.

**Comment by lognaturel** [comment]
I think this is a PowerBI issue: https://community.powerbi.com/t5/Desktop/GeoJSON-through-OData/td-p/425604

**Comment by issa-tseng** [comment]
i am almost completely certain something else happened there then. collect is actually the odd one out here for being lat then lon; the standard across the entire geospatial field is actually lon then lat, because that’s x then y. 

i give it to pbi in that order for that reason. it’s to the spec.

**Comment by lognaturel** [comment]
> i give it to pbi in that order for that reason. it’s to the spec.

The problem is that PowerBI doesn't support GeoJSON. It either interprets it as lat, lon or somehow gets other coordinates out of it.
