### ISSUE TITLE
Briefcase CLI - Password/Pem during export of project level encrypted data

### ISSUE THREAD

**Issue by chrissyhroberts** [getodk/central#174]
#### Software versions
Briefcase v1.17.4

#### Problem description

Working with a project level encrypted data set on ODK Central that has been downloaded through ODK Briefcase, the ODK Briefcase CLI appears to have no method to export data as there is no PEM file for the data set and no option for entering a decryption passphrase.

#### Steps to reproduce the problem

Create a project level encrypted dataset
Download with Briefcase and try to export

#### Expected behavior

No cypher warning

**Comment by lognaturel** [comment]
This is more about rethinking how Central makes project-level encrypted data available so I've moved the issue. It's not immediately actionable so I'll close it for now but it will be available through search. Thanks for detailing what you need and why, @chrissyhroberts.
