### ISSUE TITLE
Upload offline XML submission to ODK Central Server manually

### ISSUE THREAD

**Issue by 50shashwat** [getodk/central#180]
There are some issues with uploading the recorded form to the server. So I want to upload the forms manually by importing each XML submission record saved in the internal storage of the application and upload it to the central server. 

The option used to be there in ODK aggregate but in central it's not showing anywhere.

**Comment by lognaturel** [comment]
Please use [ODK Briefcase](https://docs.getodk.org/briefcase-intro/). If you think the upload issue might be related to a client bug, it would be good to know about that as well. In general, please start on [the form](https://forum.getodk.org) if you need help so more people in the community can be involved!
