### ISSUE TITLE
Unable to download submission

### ISSUE THREAD

**Issue by raynus** [getodk/central#192]
Hi 
I've just installed the ODK Central 1.1.1 on Ubuntu 20.04 VM on Windows 10 host as a local server.
It's a fresh install using Docker compose on Ubuntu.

The form was published, and successfully submitting data from mobile devices. 

But the CSV and zip file submssion download end up with error 403.1, even with the administrator account.
![image](https://user-images.githubusercontent.com/8155495/103759018-a1a76600-5045-11eb-882e-7e5f0fb7b612.png)

"{"message":"The authenticated actor does not have rights to perform that action.","code":403.1}"
![image](https://user-images.githubusercontent.com/8155495/103758955-8ccad280-5045-11eb-911c-9e88249b9c01.png)

Any suggestion?

**Comment by matthew-white** [comment]
Hi @raynus! That functionality uses cookie-based authentication, which only works under HTTPS.

- Are you using HTTPS?
- Are cookies enabled in your browser?

By the way, for the future, the ODK forum is the best place to start most conversations: discussion there is visible to more users and may benefit future users.

**Comment by matthew-white** [comment]
I also remembered that there are a few threads in the forum might be relevant here. This one might be a good place to start:

[SSL issue with Central on my internal network](https://forum.getodk.org/t/ssl-issue-with-central-on-my-internal-network/25648)

**Comment by raynus** [comment]
Hi Matthew

Thank you for your suggestion, I will also post my question to the forum.

To answer your questions.

Yes, I'm using HTTPS on a public domain name and the cookies was enable. Everything works fine including the Enketo web-form submission, except for the submission download.

I follow the installation instruction as mentioned in https://docs.getodk.org/central-install-digital-ocean/

**Comment by matthew-white** [comment]
Thanks for posting to the forum! (Linking to the forum thread [here](https://forum.getodk.org/t/unable-to-download-submission-from-odk-central/31908).) I'll go ahead and close the issue here.
