### ISSUE TITLE
Nginx creates encryption keys on every restart

### ISSUE THREAD

**Issue by mattelacchiato** [getodk/central#199]
When I start `docker-compose up -d` for the first time, nginx generates a private key:
```
nginx                 | diffie hellman private key does not exist; creating..
nginx                 | Generating DH parameters, 2048 bit long safe prime, generator 2
nginx                 | This is going to take a long time
```

When I shut the server down with `docker-compose down` and start again with `docker-compose up -d`, the keys are generated again (same message). Since this really takes several minutes, this is quite annoing. 

I guess, the nginx keys could be saved in a volume to prevent re-generation.

**Comment by mattelacchiato** [comment]
Same for the certificates:
```
nginx                 | Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new order :: too many certificates already issued for exact set of domains: central-test.apps.soilandmore.com: see https://letsencrypt.org/docs/rate-limits/
```

**Comment by lognaturel** [comment]
Can you please tell us more about why you are doing a down? This is a dramatic action intended to throw everything away so I think that’s the right behavior.

We have a note about not using down (unless you really do want to start from scratch) at https://docs.getodk.org/central-install/.

**Comment by mattelacchiato** [comment]
Oh, sorry, didn't see that... It was just how I expect docker-compose to work from other projects: Application state is stored in persistent volumes and I can throw the images away at any time... (and move to a different machine for example)
