### ISSUE TITLE
Can not install on windows

### ISSUE THREAD

**Issue by hussain1368** [getodk/central#200]
Hello,
Trying to install on windows using `docker-compose build`. Facing below error:
```
Step 3/19 : RUN files/prebuild/write-version.sh
 ---> Running in eccdc3daa0f3
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
ERROR: Service 'nginx' failed to build : The command '/bin/sh -c files/prebuild/write-version.sh' returned a non-zero code: 128
```
Is there any windows specific configuration I should take care of?
I think some thing needs to be changed here in `write-version.sh`:
```
#!/bin/sh

{ echo "versions:"; git rev-parse HEAD; git submodule; } > /tmp/version.txt
```

**Comment by hussain1368** [comment]
After deleting every thing and pulling a fresh clone the error change to:
```
Step 3/19 : RUN files/prebuild/write-version.sh
 ---> Running in 37743973b02e
/bin/sh: 1: files/prebuild/write-version.sh: not found
ERROR: Service 'nginx' failed to build : The command '/bin/sh -c files/prebuild/write-version.sh' returned a non-zero code: 127
```

**Comment by hussain1368** [comment]
Solved.
https://forum.getodk.org/t/odk-central-build-error/29523/18

**Comment by hussain1368** [comment]
After following instructions in the above link I was able to finish installation. However when trying to run `docker-compose up -d` I notice that nginx is showing (unhealthy). I opened a topic in the forum as well, but thought would be better to post the issue here as well. Appreciate if anyone can help. Thanks

**Comment by hussain1368** [comment]
The issue resolved by changing below configurations in `.env ` file:
```
SSL_TYPE=selfsign
DOMAIN=localhost
```
I can visit the login screen in the browser. but there is a tiny problem which I receive and SSL warning from the browser meaning the SSL is not set properly. Any idea how can I resolve that in windows?

**Comment by yanokwa** [comment]
Glad to see you are making progress, @hussain1368. The forum is the best place to post issues like these, so I'm closing this and we'll respond to your posts on the forum.

**Comment by hussain1368** [comment]
Thank you @yanokwa . Hope to hear soon from ODK team in the forum.
BR
