### ISSUE TITLE
Implement $select for OData

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#205]
This issue is to add support for the OData `$select` query parameter to Backend. This would be limited to direct column references; no expressions would be supported.

As part of this issue, `$select` should also be used in Frontend:

- For the submissions table, request just the columns selected to be shown in the table.
- For the submission detail page, don't request most of the form data. (I think we just need `__id`, `__system`, and `meta`.)

**Comment by lognaturel** [comment]
Related to https://github.com/getodk/central-backend/issues/83.

**Comment by matthew-white** [comment]
Closed by getodk/central-backend#494 and getodk/central-frontend#714.
