### ISSUE TITLE
Enable configuring of Enketo's Google API key 

### ISSUE THREAD

**Issue by yanokwa** [getodk/central#206]
Currently, Enketo running on Central does not have geocoding support because there is no API key passed in.

The key can be found at https://github.com/enketo/enketo-express/blob/master/config/default-config.json#L47 and description of its usage is at https://enketo.github.io/enketo-express/tutorial-10-configure.html

To be explicit, we should not set a default API key because that costs ODK. We just want to make it possible for self-hosters who want to get their own keys to do so. For ODK Cloud customers, we'll enable geocoding for them automagically.

**Comment by issa-tseng** [comment]
where do you feel this option is best configured? `.env`? `files/*`? something else?

**Comment by yanokwa** [comment]
This question required a surprising amount of thinking.

I think given that this is configuring an external service (Google Maps) and it's mostly a nice to have, I'd vote that we document how to make this change `central/files/enketo/config.json.template` in the docs (Using a Custom Enketo Configuration).
