### ISSUE TITLE
Setting a form version or project-level encryption through Central means XLSForm definition is unavailable with the latest published form version

### ISSUE THREAD

**Issue by JustinSteventon** [getodk/central#207]
When I have multiple versions of a form (all uploaded as xlsx), only the first one is available as xlsx.

The documentation suggests that it will always be possible to get at the XLSX that was uploaded:
https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/'-individual-form/retrieving-form-xls(x)
"If a Form was created with an Excel file (.xls or .xlsx), you can get that file back by adding .xls or .xlsx as appropriate to the Form resource path."

**Comment by lognaturel** [comment]
@JustinSteventon are you running from an unreleased commit (e.g. directly from `master`)? If so, we are aware of it and will fix it for the next release.

**Comment by JustinSteventon** [comment]
Great! I am using sandbox.getodk.cloud.

**Comment by lognaturel** [comment]
In that case, it's not the issue I'm thinking of. Have you either turned on project-level encryption or set the form version through Central rather than through the form definition? We do know that both of those will result in the XLSForm not being available for the new version. This is something we want to address soon but don't have an ETA for yet.

**Comment by JustinSteventon** [comment]
Okay. I am just uploading and publishing multiple versions of an XLSX (without any versioning info) and then observing that the API does not let me get the XLSX for all but the first version.

**Comment by lognaturel** [comment]
> without any versioning info

Can you say more about this? Central requires a different version on each publish. There should be two options -- either you set a new version in the XLSForm itself or you supply a new version string directly to Central. If you set the version string in the new XLSForm you upload, we expect that you can get that new version's XLSForm. If you set the version through frontend, we know there's a bug that prevents getting the XLSForm for that new version.

**Comment by JustinSteventon** [comment]
Yes, I'm setting the version through the frontend when I upload a new draft.

**Comment by lognaturel** [comment]
Got it. This is something we know about but it looks like we don't have an issue for it yet. I'll change your issue title slightly to broaden its scope.

We don't yet have a fix for this scheduled but will keep this issue updated as we know more. If you [set the version](https://xlsform.org/en/#settings-worksheet) in your XLSForm, you should be able to retrieve that XLSForm.

**Comment by matthew-white** [comment]
We've made some progress on this issue. In the upcoming Central release v1.3, the XLSForm will continue to be offered after a draft is created, as well as if the form version name/string is changed as the draft is published. This change was made in getodk/central-backend#395 (getodk/central-backend@4d5619cdd52f5a734ee255fb607832ce59a1bc02). We're still working on a related case, whereby the XLSForm won't continue to be offered after the project switches to managed encryption: getodk/central-backend#401.

Now that the main case is fixed for the coming release, I'll go ahead and close this issue. The status of the managed-encryption case can be tracked in the other issue.
