### ISSUE TITLE
Filtering server audit log by some top-level items doesn't work

### ISSUE THREAD

**Issue by yanokwa** [getodk/central#208]
Using Central v1.1.2.

Filter by App User Actions - No actions found.
<img width="892" alt="Screen Shot 2021-04-08 at 11 43 04" src="https://user-images.githubusercontent.com/32369/114079926-98ee4800-985f-11eb-90d2-83534b2023c3.png">

Filter by App User Actions: Create - An action found
<img width="988" alt="Screen Shot 2021-04-08 at 11 42 59" src="https://user-images.githubusercontent.com/32369/114079973-aa375480-985f-11eb-9413-875e48e8000b.png">

I expect the top-level item to include all the actions. I see this behavior in App User and Public Access Actions links. Doesn't seem to happen with Web User or Form Actions.

**Comment by lognaturel** [comment]
Oh, hah, you're right. Weird coincidence.

**Comment by matthew-white** [comment]
Closed by getodk/central-backend#348.
