### ISSUE TITLE
$wkt=true option skip GPS accuracy from json

### ISSUE THREAD

**Issue by mathieubossaert** [getodk/central#215]
I just realized exporting data from central with the $wkt option set to true hide the accuracy property from the exported data :+1: 
here the same data pulled without $wkt option : 
```json
{"__id":"391b32f3b90123e8c4ddccda97453fcd86345e06","__Submissions-id":"uuid:b7eff1c5-5f77-4820-8866-f089b47196ef","localites":{"loc":{"heure_localite":"à 10:56","methode_geo":"point","longitude":null,"latitude":null,"point":{"type":"Point","coordinates":[3.8887022,43.7195988,141.89444622492272],"properties":{"accuracy":3.9000000953674316}},"ligne":null,"longueur_ligne":null,"longueur_ligne_arrondie":null,"polygone":null,"surface_polygone":null,"surface_polygone_arrondie":null},"observations@odata.navigationLink":"Submissions('uuid:b7eff1c5-5f77-4820-8866-f089b47196ef')/emplacements('391b32f3b90123e8c4ddccda97453fcd86345e06')/localites/observations"}}
```
and with $wkt option set to true : 

```json
{"__id":"391b32f3b90123e8c4ddccda97453fcd86345e06","__Submissions-id":"uuid:b7eff1c5-5f77-4820-8866-f089b47196ef","localites":{"loc":{"heure_localite":"à 10:56","methode_geo":"point","longitude":null,"latitude":null,"point":"POINT (3.8887022 43.7195988 141.89444622492272)","ligne":null,"longueur_ligne":null,"longueur_ligne_arrondie":null,"polygone":null,"surface_polygone":null,"surface_polygone_arrondie":null},"observations@odata.navigationLink":"Submissions('uuid:b7eff1c5-5f77-4820-8866-f089b47196ef')/emplacements('391b32f3b90123e8c4ddccda97453fcd86345e06')/localites/observations"}}
```

**Comment by issa-tseng** [comment]
hey @mathieubossaert : WKT does not support representing accuracy, unfortunately. actually, geojson doesn't either, we just supply it as additional metadata. apologies, and please reopen if you find that i'm wrong. i see that WKT CRS supports "accuracy" but it's the accuracy of the CRS transform, not of each individual point.

**Comment by mathieubossaert** [comment]
Hi @issa-tseng ,
I wondering if it was possible to had the extra metadata for both geojson and wkt representation in a specific metadata column ?

**Comment by issa-tseng** [comment]
hey mathieu:

i understand your need. it’s vital and we’ll discuss how to address it internally. but i also want to warn you, this will be awkward to solve. it might take a moment and the result may be annoying to use.

**Comment by mathieubossaert** [comment]
Just a suggestion to have same information level with both geojson and WKT but if we need accuracy value, let's get geojson from OData.
