### ISSUE TITLE
ODK Central with https on other port than 443

### ISSUE THREAD

**Issue by 50shashwat** [getodk/central#229]
I am setting up ODK-central on Windows Server with IIS. I have changed the SSL port to 8443 from .env file. Also the server was having restricted internet connection so used proxy server and used all the container to use proxy to download all the packages and repository inside the container.

After setting up and starting all the containers its failed to fetch SSL certificate from lets-encrypt, so i have tried to use Self-Sign certificate from .env and rebuilt the image but that too doesn't work. I have also updated the port map variable from yml file to guest and host mapping being 8443:443 and port 8090:80.

`After editing nginx configuration i am able to run it on HTTP port over 8090 but HTTPS port over 8443 always timed out.`

I even tried installing lynx terminal browser and tried it on inside docker-nginx container but that too timed out. 

Any Idea about redirecting all https request allow to over 8443 port.

Also I am unable to set password using odk-cmd command to admin user.

**Comment by 50shashwat** [comment]
If there is any documentation regarding manual installation of each package without using docker configuration. As I want to expose PostgreSQL to Metabase service and docker seems to be blocking any other request than within the docker containers for postgreSQL.

**Comment by lognaturel** [comment]
Please direct usage questions to [the forum](https://forum.getodk.org/). The core team doesn't typically provide support for installations that differ from [installation instructions](https://docs.getodk.org/central-setup/) but someone in the community may have tried related things and have some suggestions for you.
