### ISSUE TITLE
Move from staticfloat/docker-nginx-certbot because it is not being maintained

### ISSUE THREAD

**Issue by yanokwa** [getodk/central#233]
https://github.com/staticfloat/docker-nginx-certbot/commits/master is now in maintenance mode. He recommends switching to https://github.com/JonasAlfredsson/docker-nginx-certbot/. https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/good_to_know.md#help-migrating-from-staticfloats-image has some migration instructions.

**Comment by issa-tseng** [comment]
see #230

https://github.com/getodk/central/pull/230/commits/87ad90a5d45122c5e9caae6068e59c6b7f8935a0

**Comment by yanokwa** [comment]
😓
