### ISSUE TITLE
Save user agent that sent each submission

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#254]
It'd be useful to indicate the user agent that sent each submission. @yanokwa writes on Slack:

> [I]f you know there is a bug in Collect that affected the data collection, then you could adjust your analysis.

@lognaturel writes:

> For Collect [the user agent] includes Collect version, Android version and device, all of which can have impact on behavior.

and:

> I believe Enketo populates all the things it should but if not we can make it do so.

This feature would entail saving the user agent that sent the submission, probably similar to what's done for device ID. The user agent would then be exported in the CSV and over OData. (I just checked, and it looks like we export device ID in both places.) We could also consider surfacing the user agent in Frontend, probably on the submission details page.

**Comment by lognaturel** [comment]
Related [forum conversation](https://forum.getodk.org/t/possible-to-transmit-odk-collect-version-to-aggregate/25661)

**Comment by matthew-white** [comment]
Closed by getodk/central-backend#432.
