### ISSUE TITLE
Helm charts for ODK Central

### ISSUE THREAD

**Issue by truthfool** [getodk/central#272]
It would be of great help if helm charts are provided for ODK Central for deployment in kubernetes cluster.
The steps mentioned in : 
[https://github.com/dbca-wa/central/blob/master/README_k8s.md](https://github.com/dbca-wa/central/blob/master/README_k8s.md)
It did not work for me using `kompose` . After conversion and deploying to cluster each pod had different issues.

**Comment by matthew-white** [comment]
We don't officially support Kubernetes setups. However, @florianm may be able to comment on this, since I believe he forked dbca-wa/central. I'm going to go ahead and close this issue in order to keep things organized, but feel free to continue the discussion here.

**Comment by truthfool** [comment]
Will the ODK team support Kubernetes in the future?
Our team needs it to be on K8s as well as AWS server so any chance to helm me out on the part?
I have written out basic manifest files for deployment.But it is showing Page not found error on port forward.
Perhaps anyone can take a look into it : [](https://github.com/truthfool/odk-helm-chart)

**Comment by matthew-white** [comment]
We have some documentation about how to install on [AWS](https://docs.getodk.org/central-install/). However, we don't currently have plans to support Kubernetes. Our team is small, so our ability to support a variety of setups is limited. We encourage users to use our official Docker setup if possible. If you haven't already, you could also try searching the [ODK Forum](https://forum.getodk.org/) for strategies that others have tried (or you could start a new topic).

**Comment by florianm** [comment]
Quick note - the kompose approach broke at Central 0.7 when Enketo got included. Search for mattelacchiato on the forum, he worked on a k8s compatible refactor and wanted to send a PR.

**Comment by truthfool** [comment]
[https://forum.getodk.org/t/host-odk-central-docker-images-on-github-container-registry/29812/15](https://forum.getodk.org/t/host-odk-central-docker-images-on-github-container-registry/29812/15) Is this the forum?
