### ISSUE TITLE
Why docker-compose intentionally kept postgres volumes as default ?

### ISSUE THREAD

**Issue by 50shashwat** [getodk/central#283]
I was working on exporting the data from postgres but my existing vm doesn't had that much space in it. so i tried attaching additional volume to postgres volume but the data folder there was not mounted to any specific space. so any change in docker-compose.yml would result in destroying of the whole database. My question is : Is this configuration intentionally kept ?

Also deleting the form data doesn't do anything and keeps saving the data on server. Why there is no option for deleting the data ?

**Comment by yanokwa** [comment]
Support issues should go to https://forum.getodk.org/c/support/6.
