### ISSUE TITLE
HSTS: set Strict-Transport-Security header at root path

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central#303]
HTTP requests are forwarded to HTTPS, so should probably be using HSTS.

Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

**Comment by yanokwa** [comment]
We are using HSTS: https://github.com/getodk/central/blob/master/files/nginx/odk.conf.template#L16

You just don't see it if you hit the root domain. You have to prepend`/v1`. See https://github.com/getodk/central/pull/287#issuecomment-1205848754 for more.

**Comment by alxndrsn** [comment]
:+1: issue title updated

**Comment by lognaturel** [comment]
@alxndrsn Could you please take over https://github.com/getodk/central/pull/287/files? I think the way CSP is configured will have the same issue.

**Comment by alxndrsn** [comment]
Seems like various headers which may be expected to still be applied in `location` blocks are not inherited from the `server` block:

>  There could be several `add_header` directives. These directives are inherited from the previous configuration level if and **only if there are no `add_header` directives defined on the current level**. 
> -- _https://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header_

For instance the `add_header Cache-Control no-cache` call at https://github.com/getodk/central/blob/master/files/nginx/odk.conf.template#L58 will override the `add_header Strict-Transport-Security "max-age=63072000" always` at https://github.com/getodk/central/blob/master/files/nginx/odk.conf.template#L16.

**Comment by alxndrsn** [comment]
Seems like the options for fixing this are:

* duplicating security headers in any `location` block which defines other headers
* moving security headers to a separate conf file, and then adding e.g. `include security-headers.nginx.conf;` in the `server` block and any `location` block which defines headers
* add e.g. https://github.com/openresty/headers-more-nginx-module#description to allow for header inheritance from `server` to `location`

**Comment by matthew-white** [comment]
Closed by #308.
