### ISSUE TITLE
Update Sentry ingestion URLs (deadline: Nov 1 2022)

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central#311]
> On November 1 [2022] ... event ingestion will be disabled on legacy ingestion endpoints - `https://sentry.io` and `https://app.getsentry.com`.
>
> -- _https://blog.sentry.io/2022/08/22/deprecating-tls-1-0-and-1-1_

This URL is currently set in `central-backend` at https://github.com/getodk/central-backend/blob/4e41e719ca40a122a14bf6a366dab7d37d6cc1d6/lib/external/sentry.js#L120.

As per https://blog.sentry.io/2022/08/22/deprecating-tls-1-0-and-1-1#deprecating-ingestion-endpoints, it looks like the "organization subdomain" will need to be added as a config option at: https://github.com/getodk/central/blob/63cfab894cd619a703a1a38a00756f864e58b42b/files/service/config.json.template#L30-L33

A corresponding central-backend change will also be required (filed at https://github.com/getodk/central-backend/issues/584).

**Comment by matthew-white** [comment]
Thanks for filing this, @alxndrsn!

I guess this means that we'll stop receiving events from old versions of Central (getodk/central-backend#547), at least for one release!

**Comment by matthew-white** [comment]
Closed by #312 and getodk/central-backend#585.
