### ISSUE TITLE
Deployment ODk Central parallel with Apache and tomcat

### ISSUE THREAD

**Issue by Abraziq** [getodk/central#319]
Hello,

Recently I purchased a **VPS server**. initially, I configured the Apache and Tomcat server including the ODK aggregate server it's working, and the issue is faced. So now the company wants to **odk-central** also on the same server. I have tried too much to install and configured as well as change the same port numbers. but not succeed. 

I am requesting to you facilitate me to configure odk-central on the same server and where to change the configuration plz guide me. hope you understand my query.

Thanks
Abdul Raziq

**Comment by matthew-white** [comment]
Hi @Abraziq! Thanks for taking the time to file an issue on GitHub. The ODK team uses GitHub issues for internal project management. We ask that users post support requests to the [ODK Forum](https://forum.getodk.org/c/support/6). Thank you!
