### ISSUE TITLE
Move pm2 dependency to central-backend

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#336]
Right now, we install `pm2` in this repository:

https://github.com/getodk/central/blob/da62679fe138eb89b42fcc2d9f61ae9beca9d67b/service.dockerfile#L14

However, if it's possible, I think that there would be benefits to moving the dependency to the `central-backend` repository, where we house our other npm dependencies for Backend:

- We would be more likely to remember to update `pm2`.
- We would receive automated security alerts about `pm2`.

We moved from `naught` to `pm2` in b105743365e628303644aa4a0a9f2a986baea1e0 and getodk/central-backend#395. It looks like `naught` was installed in `central-backend`.

**Comment by alxndrsn** [comment]
Another advantage: the current approach does not pin the `pm2` version.

**Comment by matthew-white** [comment]
I think pinning the version is the most important thing! That's going to be done as part of #329.
