### ISSUE TITLE
nginx 404 upon requesting Enketo preview on existing forms

### ISSUE THREAD

**Issue by tkraan** [getodk/central#356]
when we want to preview a form through the enketo service we experience a 404 error in the nginx service:

for example:
`nginx-798f88967-wqkmf nginx 10.244.110.136 - - [23/Nov/2022:15:13:05 +0000] "GET /-/css/theme-kobo.css HTTP/1.1" 304 0 "https:/xxx/-/preview/UmXHPCRRUxn2M7kY3OK1jcR5LyYxR3u" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0"
nginx-798f88967-wqkmf nginx 10.244.110.136 - - [23/Nov/2022:15:13:05 +0000] "GET /-/fonts/OpenSans-Bold-webfont.woff HTTP/1.1" 304 0 "https://xxxl/-/preview/UmXHPCRRUxn2M7kY3OK1jcR5LyYxR3u" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0"
nginx-798f88967-wqkmf nginx 10.244.110.136 - - [23/Nov/2022:15:13:05 +0000] "GET /-/fonts/OpenSans-Regular-webfont.woff HTTP/1.1" 304 0 "https://xxx/-/preview/UmXHPCRRUxn2M7kY3OK1jcR5LyYxR3u" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0"
nginx-798f88967-wqkmf nginx 10.244.110.136 - - [23/Nov/2022:15:13:05 +0000] "GET /-/fonts/fontawesome-webfont.woff?v=4.6.2 HTTP/1.1" 304 0 "https://xxx/-/preview/UmXHPCRRUxn2M7kY3OK1jcR5LyYxR3u" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0"
nginx-798f88967-wqkmf nginx 10.244.110.136 - - [23/Nov/2022:15:13:05 +0000] "GET /-/js/build/enketo-webform.js HTTP/1.1" 304 0 "https://xxx/-/preview/UmXHPCRRUxn2M7kY3OK1jcR5LyYxR3u" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0"
nginx-798f88967-wqkmf nginx 10.244.110.136 - - [23/Nov/2022:15:13:05 +0000] "GET /-/css/theme-kobo.print.css HTTP/1.1" 200 2500 "https://xxx/-/preview/UmXHPCRRUxn2M7kY3OK1jcR5LyYxR3u" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0"
nginx-798f88967-wqkmf nginx 10.244.110.136 - - [23/Nov/2022:15:13:05 +0000] "GET /-/locales/build/en/translation-combined.json HTTP/1.1" 304 0 "https://xxx/-/preview/UmXHPCRRUxn2M7kY3OK1jcR5LyYxR3u" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0"
nginx-798f88967-wqkmf nginx 10.244.110.136 - - [23/Nov/2022:15:13:05 +0000] "POST /-/transform/xform/UmXHPCRRUxn2M7kY3OK1jcR5LyYxR3u HTTP/1.1" 404 67 "https://xxx/-/preview/UmXHPCRRUxn2M7kY3OK1jcR5LyYxR3u" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0"`

Newly created forms do not have this problem.

**Comment by yanokwa** [comment]
Please post support issues at https://forum.getodk.org/c/support
