### ISSUE TITLE
Offline images missing in enketo-express

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central#370]
`enketo-express` hardcodes `base-path` into CSS when creating docker images:

https://github.com/enketo/enketo-express/blob/ad78c860b5a0a5cb3ec0173b7c2609a501ac4661/Dockerfile#L11

:arrow_double_down: 

https://github.com/enketo/enketo-express/blob/ad78c860b5a0a5cb3ec0173b7c2609a501ac4661/Gruntfile.js#L320

:arrow_double_down: 

https://github.com/enketo/enketo-express/blob/ad78c860b5a0a5cb3ec0173b7c2609a501ac4661/Gruntfile.js#L328

:arrow_double_down: 

https://github.com/enketo/enketo-express/blob/ad78c860b5a0a5cb3ec0173b7c2609a501ac4661/Gruntfile.js#L259-L272

This doesn't work for central, as `base path` defaults to empty string.

Some options:

* change the default value of `base path` to `-`
* create a special central-friendly `enketo-express` docker image with `config.server['base path']` hardcoded to `-`
* regenerate SASS (or the variables file?) at express startup

**Comment by lognaturel** [comment]
Arg, that's so frustrating!
