### ISSUE TITLE
Bug: docker-compose.yml is using anonymous volumes which are not mounted on new runs

### ISSUE THREAD

**Issue by tushar5526** [getodk/central#373]
More on this: https://github.com/docker/compose/issues/7444

Each time we do a `docker-compose up` new anonymous docker volume is generated and mounted, the older volume is not deleted but left as a dangling volume in the system. 

https://github.com/tushar5526/central/blob/master/docker-compose.yml#L6

Fix: To name the anonymous volume

**Comment by tushar5526** [comment]
I will make a quick PR for it.

**Comment by yanokwa** [comment]
The issue of migrating data from anonymous volumes to named volumes has to be solved first before we add a name to the docker-compose file. If we don't then, users who upgrade will have installs without any of their existing data. How do you propose we solve that issue?

**Comment by lognaturel** [comment]
> Each time we do a docker-compose up

It sounds like the problem here is more that you're using `down` which is aggressive and should not generally be needed for Central administration. Have you read the first warning at https://docs.getodk.org/central-install/?

**Comment by matthew-white** [comment]
Just wanted to link to #203, which provides some related context.

**Comment by tushar5526** [comment]
>  Have you read the first warning at https://docs.getodk.org/central-install/?

Thanks for the doc link. We didn't do a `docker-compose` down, instead, we had to restart docker due to some config changes. The containers stopped and someone did a container prune to remove all stopped containers on the server and the container was lost and the anonymous volume was also left as a dangling volume. 

Similarly, there could be many cases, when either due to system restart or docker restart, the containers of service might get removed or deleted. Also, if there are multiple engineers using the same server, each one of them has to know about this behaviour of ODK, or else they would end up removing all the production data if they do a docker-compose down or remove the containers directly. 

Almost every service I came across uses named volumes to persist data. Docker itself doesn't remove volumes on docker-compose down as containers are considered to be stateless.

  
> users who upgrade will have installs without any of their existing data. How do you propose we solve that issue?

I don't think there is any clean way to do this, but after we accidentally removed the odk containers, we had to find the anonymous volume from the default docker volume directory  `/var/lib/docker/volumes/<hash_name>/_data`. Copy this folder to somewhere in our system and mount the folder in the `db` service's mount directory in the `docker_compose.yml`. 

This is how we recovered our prod data. 

I haven't tested if naming an anonymous volume would persist the data of the anonymous volume or create a fresh volume

One more option could be to name the anonymous volume or copy the data of the existing volume to a named volume and then in compose file use the named volume by specifying it as an `external` volume.

**Comment by lognaturel** [comment]
Thanks for the additional context, @tushar5526! We are hoping that this will be addressed as part of upgrading the postgres version because we have to copy data at that point anyway. Let's tag you on that PR once it's feeling close to ready.

**Comment by matthew-white** [comment]
Thanks for filing this issue, @tushar5526! I think that v2023.2 resolves this issue, specifically how we set up the upgrade to Postgres 14 (#343). I'm going to go ahead and close this issue, but let us know in a new issue if you think anything is still missing.
