### ISSUE TITLE
enketo, service and nginx containers are slow to stop

### ISSUE THREAD

**Issue by lognaturel** [getodk/central#416]
https://github.com/getodk/central/pull/414 attempted to speed up stopping the enketo container. I thought I had verified the change but it's still taking 10s to stop which means sigterm is failing and sigkill is sent after 10s.

I see that the service and nginx containers have the same issues.

This hasn't been a big deal because we don't tend to do a lot of maintenance synchronously and don't tend to do a lot of development with the whole Docker setup. But still, it would be a nice improvement for those containers to stop immediately, especially when iterating on ops.

**Comment by matthew-white** [comment]
Closing now that #417 has been merged and follow-up work has been filed at #419.
