### ISSUE TITLE
Account creation fails on email providers with no auth

### ISSUE THREAD

**Issue by yanokwa** [getodk/central#420]
Central v2023.2.1 

https://docs.getodk.org/central-install-digital-ocean/#using-a-custom-mail-server says we don't need user/pass in the .env.

Given an .env file with the following...
```
EMAIL_HOST=test.example.com
EMAIL_FROM=bob@example.com
```

Account creation fails with a 500. The error in the service log is "535 Authentication failed".

If I remove the auth section from https://github.com/getodk/central/blob/master/files/service/config.json.template#L18, account creation works great.

**Comment by yanokwa** [comment]
@lognaturel I think you tested this configuration, so I'm not sure if it wasn't a good test or maybe this is an issue with this specific email server. How did you verify that removing user/pass in the .env worked?

**Comment by lognaturel** [comment]
I tested on dev. I think the mail server we use for that doesn’t use username/pass? Or maybe it was the default container. For whichever one of those doesn’t require credentials, I removed them from .env but left in the template and that worked. Did you remove the vars from .env?

**Comment by yanokwa** [comment]
Yes, I removed them from .env and left them in the template. I'll try on dev when I have a moment (but you can too if you have a moment).

**Comment by yanokwa** [comment]
I bet https://github.com/getodk/central/pull/478 explains this problem, but I can't reproduce it. 

I propose we update the docs to say we require username and password. It's not a great idea to have an SMTP server, even an internal one, without a password.

**Comment by yanokwa** [comment]
With nodemailer, you can't have blank/null strings. If you have that [auth](https://github.com/getodk/central/blob/master/files/service/config.json.template#L18) section in the transportOpts, it will try to auth with blank/null strings which won't work.

To support SMTP with no auth, we either need to do some sed magic to strip that auth section out or change Central's code to check for empty username/password when calling nodemailer and skip auth. Neither of these options sound sensible to me.

I think it's much more sensible to update our docs to ask people to setup SMTP servers with auth.

**Comment by lognaturel** [comment]
Works for me, thanks!
