### ISSUE TITLE
Submissions with attachments with unicode filenames are not saved

### ISSUE THREAD

**Issue by yanokwa** [getodk/central#433]
If you have an Enketo file submission with unicode (e.g., é) the submission will go through fine, but when you try to edit the data, you'll see...

<img width="672" alt="Screenshot 2023-05-18 at 10 27 17" src="https://github.com/getodk/central/assets/32369/e10f9960-63cd-4e25-89da-6e5bac9f632b">

In the DB, I see that the blobs have no ID.

```
central=> select * from submission_attachments where "submissionDefId" = 180867;
 blobId |       name        | submissionDefId | index | isClientAudit
--------+-------------------+-----------------+-------+---------------
  14316 | file1-10_11_1.bin |          180867 |       | f
        | fîlé2-10_11_6.bin |          180867 |       | f
        | f😂le3-10_11_9.bin |          180867 |       | f

central=> select id,"contentType" from blobs where id = null;
 id | contentType
----+-------------
(0 rows)
```

The form and files I used to do the above are here:
* [files.zip](https://github.com/getodk/central/files/11509980/files.zip)
* [form.xlsx](https://github.com/getodk/central/files/11509981/form.xlsx)

This does not happen in Collect because files are renamed to a timestamp before upload.

**Comment by yanokwa** [comment]
@eyelidlessness This isn't an Enketo bug, I'm tagging you for visibility.

**Comment by matthew-white** [comment]
## Notes for the QA team

This issue can be tested using a form with a media field. This issue only comes up in Enketo, but it'd be great to verify that a submission from Collect also continues to work.

**Comment by dbemke** [comment]
I don't know if this is in the scope of this PR when the file name contains a symbol (that shouldn't contain) like $ then while editing the user sees missing image and is able to download the file (which is broken).

![Image](https://github.com/getodk/central/assets/56479916/ff35d575-d6e5-411d-beb4-45c1750358e2)

**Comment by sadiqkhoja** [comment]
File is downloadable from the Submission table:

![image](https://github.com/getodk/central/assets/447837/1a39efa2-cf10-4b04-8347-80a47c0c3280)

When I click on download icon on submission table, backend receives this request:

`/v1/projects/473/forms/build_media_1556624635/submissions/uuid%3Abe2af264-615d-4658-afa5-385158ede558/attachments/%24dollar-8_45_1.jpg`

However, URL in Enketo is `/-/media/get/1/uuid:be2af264-615d-4658-afa5-385158ede558/%24dollar-8_45_1.jpg` and it is not sending any request to backend.

This looks like Enketo issue

**Comment by dbemke** [comment]
We finished testing other characters so please let us know if the issue above will be fixed as a separate so that we can remove the needs testing label.

**Comment by matthew-white** [comment]
Yes, that will be fixed separately in Enketo, so we can remove the "needs testing" label here. Thank you for finding that issue!

**Comment by srujner** [comment]
Tested with Success!

**Comment by dbemke** [comment]
Tested with Success!
