### ISSUE TITLE
Always see Datasets tab

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#448]
See the story in the [release criteria](https://docs.google.com/document/d/1lEIp5te0-SkA9xEPwqQdf3Kp6ciTqY8UxGBosoKPK5Q/edit#heading=h.3kw9ck7neych).

**Comment by sadiqkhoja** [comment]
@getodk/testers this can be tested on staging

**Comment by srujner** [comment]
We've got two questions related to this PR:
1) "Chip identifies it as new and interesting" - Is this about pink "New!" label next to Datasets tab?
2) I think we need to extend the information that we give about project roles here to contains Datasets also, probably in this page too: https://docs.getodk.org/central-users/#central-users-web-roles but this might be a different PR, at the moment question is: Project Manager and Project Viewer can see the Datasets tab and Data Collector can't is this the correct behavior?
![Screenshot(152)](https://github.com/getodk/central/assets/85225519/d241aa22-82ef-40cc-baaa-7ce18db7a802)

**Comment by sadiqkhoja** [comment]
> "Chip identifies it as new and interesting" - Is this about pink "New!" label next to Datasets tab?
yes

> Project Manager and Project Viewer can see the Datasets tab and Data Collector can't is this the correct behavior?
yes

**Comment by srujner** [comment]
**Tested with Success!**

**Comment by dbemke** [comment]
**Tested with Success!**
