### ISSUE TITLE
Support Single Sign-on with OpenID Connect

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#449]
Creating an issue to track work on SSO:

- [Release criteria](https://docs.google.com/document/d/1lEIp5te0-SkA9xEPwqQdf3Kp6ciTqY8UxGBosoKPK5Q/edit#heading=h.a02nafhkjvhn)
- [Backend PR](https://github.com/getodk/central-backend/pull/910)
- [Frontend PR](https://github.com/getodk/central-frontend/pull/819)
- [`central` PR](https://github.com/getodk/central/pull/458)

**Comment by ktuite** [comment]
### Adventures trying SSO in dev (july 25)

- checked out backend branch
- checked out frontend branch

Note: would be nice to be rebased with master soon to get newer database migrations

Ran on the backend:
`make dev-oidc`
`make fake-oidc-server`

Ran on the frontend:
`npm run dev` and go to the usual `http://localhost:8989/`

Note: At first, things didn't quite run properly and I wasn't sure why. I got hung up on this issue for a while: On my mac, [something](https://stackoverflow.com/a/70456715) is already running on port 5000 so i changed it to another port in `Profile` and `main.nginx.conf`. Then everything ran great.

Appreciated that the fake oidc server gave me useful tips when in entered bad credentials.

**Comment by matthew-white** [comment]
The three PRs above are merged, and the QA team is now taking a look at this issue, so I'm going to go ahead and close. There are still some related to-dos that I've filed as separate issues: #477, getodk/central-backend#971, getodk/central-backend#976.

**Comment by dbemke** [comment]
Logging out on Chrome feels a bit tricky. There a few scenarios that theoretically go along with "do not centralize log out” release criteria but make it difficult to "really log out” and switch a user afterwards. 

Steps to reproduce:
1. Log in to staging on Chrome (this logs in also the browser to the account).
2. Log out of staging.
3. Click continue – the user is logged in without having to choose a user or enter a password


![Image](https://github.com/getodk/central/assets/56479916/c4f8279f-8ef7-4d59-9fce-5c401fb36648)


One thing that is not present after logging out is the ability to choose an account to which I want to log in to (e.g. the second time I want to log in to a different account). So to change the user I need to find the account that I’m currently logged in the browser (it’s possible to make it that it’s not the one visible in the header) and log out of staging and then the option to choose a user appears while logging in.
What’s more the same steps are reproducible in the incognito mode (Chrome and Firefox) – after logging out the user is not asked to enter the password.


![Image](https://github.com/getodk/central/assets/56479916/d64781f8-4b8d-404c-b516-358cf1bf330a)

**Comment by dbemke** [comment]
@alxndrsn @matthew-white @ktuite As mentioned above there are some issues with logging out and we're about to start regression testing so are these cases ok and they'll be fixed separately?
To give some more examples: 
Logging out doesn't work also while being a guest in the browser. After logging out and clicking continue the user is still logged in.
I checked the same steps with logging to my email (gmail) and the password isn't kept after logging out if the user is a guest in the browser.

**Steps to reproduce:**
1. Open Chrome, at the top right click Profile
2. Click Guest.
3. Go to staging.getodk.cloud
4. Log in to an account.
5. Log out form staging.
6. Click continue

After clicking continue the user is logged in without being asked to enter the password.

**Comment by dbemke** [comment]
I checked on Windows edge (on a virtual machine) where I don't allow saving password etc. and after logging out clicking continue also logs in the user without asking for the password.

**Comment by srujner** [comment]
Following the Slack conversation, we are closing this pull request as **tested with success**. 
If after further discussions, changes are needed, they will be created in the new Pull Request.

**Comment by dbemke** [comment]
Tested with success!
