### ISSUE TITLE
Remove "Coming soon" from Role Settings 

### ISSUE THREAD

**Issue by alyblenkin** [getodk/central#450]
**Problem:**
"Coming soon" has been coming soon for an eternity. 

A user brought this up in a research session. 

**Solution:**
Please remove it 🙏 

Now we will have a chip for introducing new features, which I spoke to @sadiqkhoja (connected to https://github.com/getodk/central/issues/448#issue-1808200045)

![image](https://github.com/getodk/central/assets/7871340/6e4488de-c71b-48a3-b840-c9bb57b72e02)

**Comment by matthew-white** [comment]
What do you think about removing the tab entirely? I think it could be confusing if the tab is disabled without an explanation.

**Comment by alyblenkin** [comment]
I think so! Having the tab is misleading when you can't do anything anyway.

**Comment by matthew-white** [comment]
We don't usually show just one tab, so if we remove the "Role Settings" tab, we'd probably remove the two tabs altogether. Does that sound right?

**Comment by alyblenkin** [comment]
You're right, it's not ideal to have one tab. However, we only show one tab under System, so we could get away with it for now. We plan to start designing the user evolution work soon, so I don't want it to keep changing things for users.

**Comment by matthew-white** [comment]
@getodk/testers, this issue is now ready for verification. This change has been deployed to the staging server. When you navigate to the users page, you should continue to see the "Web Users" tab. However, you should not see the "Role Settings" tab.

**Comment by srujner** [comment]
**Tested with Success!**
