### ISSUE TITLE
Can't replace media files in the Form Attachments tab

### ISSUE THREAD

**Issue by srujner** [getodk/central#459]
#### Problem description
Error code 500 is visible after trying to replace the media files in the Form Attachments tab
#### URL of the page
https://test.getodk.cloud/#/projects/364/forms/mediaTest/draft/attachments
#### Steps to reproduce the problem
1. Use the URL from above
2. Log into the application if needed
3. Click on the Upload files button
4. Choose files or Drag and Drop files, that will have a different e.g Pictures but the name of the file will be the same.
5. Something went wrong: error code 500. will appear
#### Screenshot
![Screenshot(150)](https://github.com/getodk/central/assets/85225519/8c75effd-6dff-4744-8930-48bb0e0d4d6a)

#### Expected behavior
The media files should be replaced without any errors
#### Central version shown in version.txt

906addf66af230735e501ad73a1269012fdd7a5a (v2023.3.1)
+330132cf1ecb824b1fb88894287cb8edb5acefa5 client (v2023.3.0-2-g330132cf)
 ba6ee474f431b48e885fb035c9266792f06d0ad7 server (v2023.3.1)
#### Browser version
Firefox 116.0.2 (64-bit)
#### Around when did you see the problem (in UTC)?
9:00 AM
#### Other notes (if any)
I was able to reproduce it on different forms with media files e.g "defaultImage" from the same project

**Comment by matthew-white** [comment]
I think I caused this by attempting a direct backup, which caused the server to run out of disk space. Sorry about that! Now that the server has disk space again, are you able to upload form attachments again?

**Comment by srujner** [comment]
Yes, now it's all good, we can close the issue.
