### ISSUE TITLE
"Analyze via Odata” button isn’t disabled in an encrypted project after the first submission via Enketo

### ISSUE THREAD

**Issue by dbemke** [getodk/central#461]
#### Problem description
"Analyze via Odata” button isn’t disabled in an encrypted project after the first submission via Enketo. If the user refreshes the website or goes back to it after e.g. going to a different tab, the button is disabled.
#### URL of the page
https://test.getodk.cloud
#### Steps to reproduce the problem
1. In an encrypted project on Central add and publish a new form.
2. Go to Submissions of the form and click "+New”.
3. Fill and submit the form.
4. Go back to Submissions, refresh the submission list and check if "Analyze via oData” button is disabled

#### Expected behavior
The button should be disabled in an encrypted project.
#### Central version shown in version.txt
versions:
906addf66af230735e501ad73a1269012fdd7a5a (v2023.3.1)
+330132cf1ecb824b1fb88894287cb8edb5acefa5 client (v2023.3.0-2-g330132cf)
 ba6ee474f431b48e885fb035c9266792f06d0ad7 server (v2023.3.1)
#### Browser version
Chrome 114.0.5735.198, Firefox 116.0.2

**Comment by matthew-white** [comment]
Thank you, @dbemke! I think this is the same issue as getodk/central-frontend#521. Does that sound right? I'll slot that issue for the next release — this is a good reminder that that issue is continuing to come up.

**Comment by dbemke** [comment]
Yes, it's the same. I remember we reported it some time ago in Google docs but I didn't know if there was an issue for that on github.

**Comment by matthew-white** [comment]
I'll go ahead and close this one, but hopefully we can solve the issue in the next release.
