### ISSUE TITLE
Include dataset related permission in docs and help text

### ISSUE THREAD

**Issue by sadiqkhoja** [getodk/central#462]
We should update following to include Dataset and Entity permissions:

https://docs.getodk.org/central-users/#central-users-web-roles

![image](https://github.com/getodk/central/assets/447837/6d6bafca-67db-45d3-9803-401bb6208ba8)

**Comment by matthew-white** [comment]
@lognaturel is going to work on creating a Frontend PR for this, and I'll work on updating docs.
