### ISSUE TITLE
No properties in the form creating entities, in the draft section and form overview section clicking the arrow to show properties ("0 of x properties”) shows an empty space

### ISSUE THREAD

**Issue by dbemke** [getodk/central#463]
#### Problem description
If the users removes all properties in the form creating entities, in the draft section and form overview section clicking the arrow to show properties ("0 of x properties”) shows an empty space without any information.

#### Steps to reproduce the problem
(Steps 1, 2 are optional)
1. Upload and publish a form creating entities with at least one saveto field.
2. In the form remove the saveto column so that there are no properties.
3. Create a draft of the new version of the form (without saveto fields).
4. Click the arrow next to "0 of x properties”.
#### Screenshot
![zeroproperties](https://github.com/getodk/central/assets/56479916/13d8d0dc-24c3-42e7-a98e-1c220a704849)
After clicking the arrow:
![nopropertiesunfild](https://github.com/getodk/central/assets/56479916/034dda00-009b-4256-ac2b-fa88c5a3211e)
![verviewzeropropertiesunfold](https://github.com/getodk/central/assets/56479916/6c312790-8ef8-415c-a4b5-6c9e999dcaef)

#### Expected behavior
The arrow works as expected and it’s an edge case (having 0 properties) so I'm not sure what the expected should be but maybe showing some piece of information instead of an empty space would be more user-friendly.
#### Central version shown in version.txt
versions:
906addf66af230735e501ad73a1269012fdd7a5a (v2023.3.1)
+330132cf1ecb824b1fb88894287cb8edb5acefa5 client (v2023.3.0-2-g330132cf)
 ba6ee474f431b48e885fb035c9266792f06d0ad7 server (v2023.3.1)
#### Browser version
Chrome 114.0.5735.198, Firefox 116.0.2
#### Other notes
A form without saveto fields - directors form version 1 in https://test.getodk.cloud/#/projects/436/forms/director%20entities

**Comment by matthew-white** [comment]
I'm pretty sure that getodk/central-frontend#845 resolves this.

**Comment by sadiqkhoja** [comment]
@getodk/testers this can be tested on staging environment

**Comment by dbemke** [comment]
**Tested with success!**

**Comment by srujner** [comment]
**Tested with success!**
