### ISSUE TITLE
Rename "Dataset" to "Entity List"

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#466]
Make this change in:

- [x] Frontend
  - [x] Text
  - [x] Routes
  - ~API requests~
- [x] Backend
  - ~API endpoints (should we add aliases so that it isn't a breaking change?)~
  - [x] API docs
  - Don't rename database tables
  - Maybe don't rename audit log actions?
  - Don't rename "dataset" where it is used only internally in the code (e.g., the frame name)
- [x] User docs

**Comment by matthew-white** [comment]
**Why we decided not to change the API**

@lognaturel wrote on Slack:

> But for the APIs, maybe we should also consider the option of keeping `dataset`? It’s confusing but seems like the kind of thing an API consumer could handle.

&hellip;

> We’ve decided to keep “dataset” for the spec, API, and everything dev-facing in Central. The hope is that this split will be more consistent and less confusing than a partial conversion.

I wrote:

> Along the lines of what Sadiq said, the difficulty is that it’s not just mapping /v1/projects/:id/datasets to /v1/projects/:id/entity-lists. When you link a form attachment to a dataset, you do so by specifying `"dataset": true` in the request body. For a couple of responses (project extended metadata, form attachments), `dataset` is also in the response body.

**Comment by ktuite** [comment]
I'm thinking we should update the Problems that mention Datasets. Some of them wind up passed through to frontend like [here](https://github.com/getodk/central/issues/482#issuecomment-1721324026) in the dataset property validation step.

**Comment by lognaturel** [comment]
Continuing musings from https://github.com/getodk/central/issues/482#issuecomment-1721684317. We need to decide what problem messages should be consistent with: everything else in backend or the universe outside of backend. These messages are at the edge so it's not an obvious decision. My current leaning is to keep everything in backend using 'dataset', even moving forward, and to be sure that problems that have messages with 'dataset' are explicitly handled in frontend and given localizable strings.

**Comment by matthew-white** [comment]
> I'm thinking we should update the Problems that mention Datasets.

This question was separated into its own issue, #487.
