### ISSUE TITLE
Unpublished dataset is viewable

### ISSUE THREAD

**Issue by sadiqkhoja** [getodk/central#468]
Steps to reproduce:
- Upload a Form that defines a new dataset
- Don't publish it 
- Click on the name of the dataset display on Form Status tab or directly type respective URL like https://test.getodk.cloud/#/projects/483/datasets/trees
- You would be able to see dataset details, however when you click on "Data" tab it will throw 404 error

**Comment by matthew-white** [comment]
Duplicate of #467?
