### ISSUE TITLE
Forms not updating entities are automatically linked to datasets if the name of the file is the same

### ISSUE THREAD

**Issue by dbemke** [getodk/central#471]
#### Problem description
In a project in which there is a name of entity list (dataset) the same as a file that should be uploaded along with another form (not updating entities), the entity list file is linked automatically although the form doesn’t create entities.

#### Steps to reproduce the problem
1. Publish a form creating a dataset (e.g. itemsets.csv).
[itemsets_registration.xml.zip](https://github.com/getodk/central/files/12473446/itemsets_registration.xml.zip)

2. Upload a form (not updating entities) that attaches a csv file with the same name as the dataset (e.g. itemsets.csv).
[cascading_select_external_itemsets.xml.txt](https://github.com/getodk/central/files/12473450/cascading_select_external_itemsets.xml.txt)

3. In the Draft section go to Form Attachments tab and check if the file was automatically uploaded from datasets/entity lists.
#### Screenshot
![fileUpload](https://github.com/getodk/central/assets/56479916/972e2415-3b60-4de7-bacb-b39ff0257c70)
![datsetinform](https://github.com/getodk/central/assets/56479916/2d202e45-1fd7-49b6-b7b5-06a8474de784)

#### Expected behavior
Datasets/entity lists shouldn’t be linked automatically to forms that don’t update entities.
#### Central version shown in version.txt
https://test.getodk.cloud/
versions:
906addf66af230735e501ad73a1269012fdd7a5a (v2023.3.1)
+330132cf1ecb824b1fb88894287cb8edb5acefa5 client (v2023.3.0-2-g330132cf)
 ba6ee474f431b48e885fb035c9266792f06d0ad7 server (v2023.3.1)
https://staging.getodk.cloud/
versions:
f78da7a8b7a132ad2baa794a656da6ba8e40754a (v2023.3.1-6-gf78da7a)
+f6aefcc71621a394943f91613234ba295e34cd86 client (v2023.3.0-17-gf6aefcc7)
+628ac0d14e4c772591661dbac81b1fb49a1dbce8 server (v2023.3.1-34-g628ac0d1)

#### Browser version

Chrome 114.0.5735.198, Firefox 116.0.2

**Comment by lognaturel** [comment]
> the entity list file is linked automatically although the form doesn’t create entities.

This is currently the expected behavior. Follow-up forms can attach entity lists without creating entities so we don't actually know what the user intent is. We've decided that it's pretty unlikely that a user would want to have a file with the same filename as their entity list name because that would be confusing for them. If they do need to do that for some reason, though, they can unlink the entity list.

> I also tried uploading a form (not creating entities) with itemsets.geojson file and to some point Central also considered that file as an entity list.

This is a bit stranger! It seems we should specifically look for files that have .csv extensions.

**Comment by dbemke** [comment]
I filed a separate issue.

**Comment by matthew-white** [comment]
Thanks, @dbemke! I'll go ahead and close out this issue.
