### ISSUE TITLE
“Show # total Forms/Entity lists” is not visible on the expand control. 

### ISSUE THREAD

**Issue by srujner** [getodk/central#479]
#### Problem description
During writing Test Cases for Central I noticed that under Forms and Entities there is "Show X total" on the expand control.
In the Release Criteria docs there is info: "I should see “Show # total Forms” instead of “Show # total” on the expand control".
#### URL of the page
https://staging.getodk.cloud/#/
#### Steps to reproduce the problem
1. Log in to application and navigate to the homepage
2. Notice that under Forms and Entities there is "Show X total" on the expand control.
#### Screenshot
![Screenshot(167)](https://github.com/getodk/central/assets/85225519/017d3aab-9d4f-4789-ad98-de6eb7cca574)

#### Expected behavior
Under Forms and Entities on the expand control there should be information: “Show # total Forms/Entity Lists”

#### Central version shown in version.txt
410890a506c26da287a1a3ad9251afe3a92986b0 (v2023.3.1-8-g410890a)
+78a1a9e38383e0a5a5c3134ef03fafa8cb49ac69 client (v2023.3.0-22-g78a1a9e3)
+ee9211c58bc5bcbdda7810ccb11f79b0dc29c950 server (v2023.3.1-46-gee9211c5)
#### Browser version
Firefox 117.0
#### Around when did you see the problem (in UTC)?
9:00 AM

**Comment by matthew-white** [comment]
@getodk/testers, this change is ready to be verified, on either staging or the QA server.

**Comment by srujner** [comment]
**Tested with Success!**
