### ISSUE TITLE
No passphrase dialog before downloading draft submissions in an encrypted project

### ISSUE THREAD

**Issue by dbemke** [getodk/central#492]
#### Problem description
The user is not asked to enter a passphrase before downloading draft submissions in an encrypted project. It’s possible to download the submissions but the values in the CSV table are empty (not decrypted).

#### Steps to reproduce the problem
1. Upload a draft form in an encrypted project.
2. Add some submissions.
3. Click "Download x submissions”.
4. Check the CSV file.

#### Expected behavior
The user should be asked to enter the passphrase so that the anwers get decrypted in the downloaded CSV file.
#### Central version shown in version.txt
https://staging.getodk.cloud/
versions:
0a310c619750d64519c4ce9883e08d124020975b (v2023.3.1-13-g0a310c6)
+972062f259293877ca2f718aefc83ad80979f2ca client (v2023.3.0-35-g972062f2)
+0b1272fb9935bd256f42b7debb63c48b1bd7a35f server (v2023.3.1-70-g0b1272fb)
https://sandbox.getodk.cloud/
versions:
906addf66af230735e501ad73a1269012fdd7a5a (v2023.3.1)
 676b63a62652cec57b06b622a0ef36a58fa6d6e4 client (v2023.3.0)
 ba6ee474f431b48e885fb035c9266792f06d0ad7 server (v2023.3.1)

#### Browser

Chrome and Firefox

**Comment by matthew-white** [comment]
I think this is similar to #493 and that the root cause is again getodk/central-frontend#521. For example, when I navigate to the following draft in an encrypted project, I am prompted for the passphrase: https://staging.getodk.cloud/#/projects/45/forms/familymemberscount/draft/testing. Does that sound right to you?

**Comment by dbemke** [comment]
Yes

**Comment by matthew-white** [comment]
Sounds good, I think I'll go ahead and close then. We'll address getodk/central-frontend#521 soon!
