### ISSUE TITLE
See update conflicts from home page

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#500]
See the story in the [release criteria](https://docs.google.com/document/d/1EdEDcXoJmrryFYNc56zciuQ82G_iVGBQf1UFEkWiUtw/edit#heading=h.xbnn4jtzgmh6).

**Comment by srujner** [comment]
**Tested with Success!**

**Comment by dbemke** [comment]
Tested with Success!

**Comment by issa-tseng** [comment]
let's knock the font-size from 16 to 14px and take the padding down from 2px10px to 2px7px.
