### ISSUE TITLE
See update conflicts on page of Entity Lists

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#502]
See the story in the [release criteria](https://docs.google.com/document/d/1EdEDcXoJmrryFYNc56zciuQ82G_iVGBQf1UFEkWiUtw/edit#heading=h.aunghwrifr4v).

**Comment by matthew-white** [comment]
Sorry @sadiqkhoja, I saw getodk/central-frontend#882 fly by and thought it was for this issue. I'll unassign you here.

**Comment by dbemke** [comment]
**Tested with success!**

**Comment by srujner** [comment]
**Tested with success!**
