### ISSUE TITLE
Filter by update conflicts in Entity table

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#503]
See the story in the [release criteria](https://docs.google.com/document/d/1EdEDcXoJmrryFYNc56zciuQ82G_iVGBQf1UFEkWiUtw/edit#heading=h.v80owbri6rdz).

Frontend PR: getodk/central-frontend#874
Backend PR: getodk/central-backend#1024

**Comment by matthew-white** [comment]
Things that Backend will need to do:

- Return a `__system/conflict` property over OData.
- Filter entities on that property.
- Support `$filter` for CSV downloads. (#521)

**Comment by issa-tseng** [comment]
looks good. it would be nice someday if when it's "1 of x" in the filter dropdown just show the selected option (truncated if too long).

**Comment by dbemke** [comment]
The expected design for the conflict status filtering is this?


![Image](https://github.com/getodk/central/assets/56479916/1fd00c2d-b184-4073-8e59-e56142675c97)


not the one from release criteria ( different text in the conflict status field + show columns filter)? 


![Image](https://github.com/getodk/central/assets/56479916/437f0cd7-f8bb-4f8d-9a78-7f0557fae904)

**Comment by matthew-white** [comment]
@dbemke, yes, that's currently expected. "Conflict status" will be shown below the filter, not within it. We also haven't added a column selection dropdown yet (and won't as part of this release).

**Comment by dbemke** [comment]
**Tested with success!**
