### ISSUE TITLE
See update conflicts in Entity feed

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#507]
See the story in the [release criteria](https://docs.google.com/document/d/1EdEDcXoJmrryFYNc56zciuQ82G_iVGBQf1UFEkWiUtw/edit#heading=h.pcbjmlmke0fj).

---

Related:

- #511
- getodk/central-backend#1028
- getodk/central-frontend#879
- #533
- #531
- #532

**Comment by matthew-white** [comment]
Related Frontend PR: getodk/central-frontend#879

**Comment by issa-tseng** [comment]
seems fine

**Comment by srujner** [comment]
**Tested with Success!**
