### ISSUE TITLE
Tests and error handling for update entity via submission

### ISSUE THREAD

**Issue by ktuite** [getodk/central#510]
Addressed in PR https://github.com/getodk/central-backend/pull/1021

Followup to https://github.com/getodk/central/issues/509

Add more tests and error handling around entity updates. 

- Error handling (entity not found, parsing errors, etc.)
- Reprocessing failed tasks
- Thorough tests

**Comment by matthew-white** [comment]
In terms of error handling and the frontend, if there's an error updating an existing entity (e.g., a parsing error), should we show that in the entity feed?

**Comment by ktuite** [comment]
From @matthew-white's comment [here](https://github.com/getodk/central-backend/pull/1005#discussion_r1341694584)
> Idea for test: what if `baseVersion` is specified together with `create`, not `update`? Is that an error, or should we just ignore `baseVersion` in that case?

**Comment by ktuite** [comment]
Comment [here](https://github.com/getodk/central-backend/pull/1005#discussion_r1341707052) - make sure to use and test `validateEntity()`
