### ISSUE TITLE
See entity update in submission feed

### ISSUE THREAD

**Issue by ktuite** [getodk/central#513]
I think this image and set of notes in the release criteria is about the entity feed:
From release criteria ([comment](https://docs.google.com/document/d/1EdEDcXoJmrryFYNc56zciuQ82G_iVGBQf1UFEkWiUtw/edit?disco=AAAA70757jU))
![unnamed](https://github.com/getodk/central/assets/76205/1d3358d2-1846-4674-b2a7-b2df708b944b)

The submission feed will also have a note about how the submission updated an entity, but it probably wont show the diff.

**Comment by matthew-white** [comment]
I think #507 covers entries in the entity feed, but that's a great point that we'll also need to update the submission feed. What do you think about making this issue just about the submission feed?

**Comment by matthew-white** [comment]
As with `entity.create` events, we'll need to handle the case where the entity is deleted.

**Comment by issa-tseng** [comment]
looks nice, only thought is maybe it should like the feed item related to the submission if it can? okay if no

**Comment by matthew-white** [comment]
Just to be sure, you mean showing the diff, as well as information about the conflict (if there is one)? I think that'd be doable.

**Comment by matthew-white** [comment]
Would it look confusing if there end up being two different types of diffs on that page? At the moment, submission diffs and entity diffs look a bit different.

**Comment by srujner** [comment]
Tested With Success!
