### ISSUE TITLE
Exclude new entity actions from nonverbose audit log

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#515]
In .5, we will add one or more new entity actions:

- Marking update conflicts as resolved
- Probably: An error updating an entity (`entity.update.error` to parallel `entity.create.error`).

We should exclude these actions from /v1/audits?action=nonverbose so that Frontend does not show them on the Server Audit Logs page.

**Comment by ktuite** [comment]
Related issue: https://github.com/getodk/central/issues/520

**Comment by ktuite** [comment]
Closing because this is covered by other issues
- not adding an update error because we're making a generic error action https://github.com/getodk/central-backend/pull/1027 
- conflict resolved action https://github.com/getodk/central-backend/pull/1023
