### ISSUE TITLE
Allow form that just updates entities to modify entity list

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#516]
I have a form that creates submissions that only update (not create) entities. When I publish the form, I should see that it modifies entity lists in the same way as normal (in the same way as uploading a form that creates submissions that create entities). If the form uses a new entity list, the entity list should be created. If the form saves to a new property of an existing entity list, the property should be added to the entity list. When I navigate to the form overview, I should see the new entity list and new properties under "N Entity Lists are updated by this Form".

Similarly, after uploading the form, but before publishing it, I should see this information on the draft status page. I should also see this information in the pop-up when I click "Publish Draft".

**Comment by ktuite** [comment]
I think the code already does this, but we should add some tests to the dataset tests that check properties.

**Comment by dbemke** [comment]
Should a form that only updates entity be shown in Connections to Forms- Forms create Entities in this Entity List?


![Image](https://github.com/getodk/central/assets/56479916/ef720eae-f01f-4666-8164-9aab6f482324)

**Comment by matthew-white** [comment]
I think it should. But I also see that the text probably has to change so that it's not about creating. I think we could say "update" instead of "create", and it would address it. CC @issa-tseng

**Comment by srujner** [comment]
Tested with success!

**Comment by dbemke** [comment]
**Tested with success!**
