### ISSUE TITLE
Submission edits can create or update an entity, but only once

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#517]
A submission should only be able to create a single entity. It should only be able to update a single entity, and it should only be able to update it once. It should not be able to both create and update. Usually, if a submission will create or update an entity, it will do so when the submission is first created (in the first version of the submission). However, if the first version does not create or update an entity, then an edit to the submission will be able to. If a submission has already created or updated an entity, then a later edit will not be able to create an entity, update a different entity, or even update the same entity. A submission gets only one chance to make changes to entities.

- [ ] https://github.com/getodk/central-backend/pull/1044 
- [ ] Backend: TODO double-check `createEntitiesFromPendingSubmissions`
- [ ] Frontend: TODO

<details>
<summary>Examples</summary>

**Example 1**

- The entity list is configured to create entities on submission receipt.
- A submission is created that does not create or update an entity.
- The submission is edited so that it does create an entity.
- An entity should be created.

**Example 2**

- The entity list is configured to create entities on submission approval.
- A submission is created that does not create or update an entity.
- The submission is approved.
- The submission is edited so that it does create an entity.
- An entity should not be created yet.
- The submission is reapproved.
- An entity should be created.

**Example 3**

- The entity list is configured to create entities on submission receipt.
- A submission is created that creates an entity.
- The submission is edited to create a new entity with a different UUID.
- A second entity should not be created.

**Example 4**

- The entity list is configured to create entities on submission receipt.
- A submission is created that creates an entity.
- The submission is edited to update a different entity.
- The second entity should not be updated.

**Example 5**

- The entity list is configured to create entities on submission receipt.
- A submission is created that creates an entity.
- The submission is edited to update the same entity.
- The entity should not be updated.

**Example 6**

- A submission is created that does not create or update an entity.
- The submission is edited to update an entity.
- The entity should be updated.

**Example 7**

- A submission is created that updates an entity.
- The submission is edited to update a different entity.
- The second entity should not be updated.

**Example 8**

- A submission is created that updates an entity.
- The submission is edited to update the same entity again (perhaps with different data).
- The entity should not be updated a second time.

**Example 9**

- A submission is created that tries to update an entity, but the specified entity does not exist. (Maybe it's been deleted.)
- The submission is edited to update a different entity.
- The second entity should be updated.

**Example 10**

- A submission is created that updates an entity.
- The submission is edited to create a new entity with a different UUID.
- The new entity should not be created.
</details>

<details>
<summary>Interesting use cases discussed on Slack</summary>

@ktuite:

> if the update was conditional and the submission is updated to toggle updating, then it will go ahead and update the entitiy

Me:

> if there’s a new form version that introduces entities for the first time

@lognaturel:

> I guess one nice thing about the current approach is in a case like what @ktuite mentioned, recovery is possible. Like if someone’s age was entered in as 17 so they weren’t entered into the study/made into an entity but actually it turns out they’re 18, it’s a very easy fix.

@lognaturel:

> I’m already imagining people adding a “hold for review” question in their forms that blocks entity creations and can be toggled in the office.

> So they can have both automatic entity creation and review as needed!

@ktuite:

> there are some negative cases we should check like… if we do the simplest thing in code and follow a similar pattern as submissions, what does that mean for submissions that get caught up on the `createEntitiesFromPendingSubmissions` flow that was just meant for entity-creating submissions? there might be some awkward/unintended behavior or it might intersect with what LN just wrote.

---
</details>

Even though many of these cases are unlikely, we've decided that we should document this behavior. @lognaturel:

> I think if we don’t want people to rely on the current behavior we should probably be explicit about it.

We also considered the following alternative (@lognaturel):

> an alternative could be something like only original versions are eligible for entity processing, never submission updates?

However, we decided to opt for the behavior described above, which is the most similar to the current behavior:

> Seems reasonable to go with what is easiest to represent consistently and documenting that.

> Don’t think there’s a strong user need that would justify more complexity.

**Comment by matthew-white** [comment]
As part of this issue, I think we'll need to update the `EntityFeedEntry` component in Frontend. Currently, when rendering an entity update, `EntityFeedEntry` decides whether it is an update via submission by checking for the presence of a `submissionCreate` property in the audit log details. If there is no `submissionCreate` property, then it is considered an API update. But in the case of an entity update via submission edit, there will also be no `submissionCreate` property. (I just checked this in the Backend code.) We should make sure that `EntityFeedEntry` handles that case and doesn't render an update via submission edit as an API update.

**Comment by matthew-white** [comment]
Related to my last comment, I think getodk/central-backend#1036 is relevant to this issue. In the case of an entity update via submission edit, maybe we could use a modified version of the `submission` property. If a `submission` property is guaranteed to be returned, including for deleted submissions, then I think we could use it for an entity update via submission edit.

**Comment by ktuite** [comment]
@getodk/testers The issue described above should be fixed now!

**Comment by srujner** [comment]
**Tested with Success!**

**Comment by dbemke** [comment]
Tested with Success!
