### ISSUE TITLE
Restrict submissions to the entity actions listed in the form

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#518]
I have an entity list and a form whose submissions create entities in the entity list. My workflow is fairly controlled: submissions create entities only after approval, and I don't use submissions to update entities. Within this context, submissions will specify a `create` attribute on the `meta/entity` field. If the submission XML is manually modified to specify an `update` attribute, then the submission should be rejected. That is, the only action attributes allowed on `meta/entity` in the submission XML should be those specified in the form XML.

I think this will be especially important once we support entity archiving. You could imagine a public link form that is allowed to create entities, but that definitely shouldn't archive entities.

**Comment by ktuite** [comment]
This would involve parsing the create/update attributes when we read the dataset definition, saving those actions in the database (in a way that is linked to the form def, so different versions of a form can do different actions), and checking those as submission-processing time.
