### ISSUE TITLE
Entity update submission processing errors get logged as create errors by worker

### ISSUE THREAD

**Issue by ktuite** [getodk/central#520]
When there is an error processing a new entity from a submission, it gets logged by the entity worker as an `entity.create.error` error that can be shown in the submission feed.

This error logging has to be reused when there is an error processing an entity _update_ from a submission, because the worker doesn't know if it's an update or create. (It needs to read the submission XML to figure that out, and the error could be with the XML). 

On the backend, we should probably change the error so it's more generic. The main purpose of this error it to expose SOME information about how a submission entity failed to get processed, so hopefully it's ok to change it?

On the frontend, we should change the messaging so it works for any kind of submission/entity processing error. 

Maybe there's something clever to be able to know if it's about a create event or update event, but that feels more complex to test and maintain, because we'd have to make it work for create, update, not sure, and any future kinds of events.

**Comment by matthew-white** [comment]
I support the idea of a single generic event rather than separate events for `entity.create.error`, `entity.update.error`, etc. Could we migrate existing `entity.create.error` events to generic `entity.error` events?
