### ISSUE TITLE
Hide some entity conflict functionality from project viewers

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#538]
This issue is to account for project viewers for the following stories in the release criteria:

- #504
- #506

See the release criteria for details about what a project viewer should and should not see.

<details>
<summary>Original issue description</summary>

Right now, a project viewer can see the "Review parallel updates" button in the entities table. Clicking the button shows a modal that allows the user to update the entity or mark it as resolved. However, project viewers can't do those things. I think we should hide the "Review parallel updates" button from project viewers. (We could use the `canUpdate` prop of the `EntityMetadataRow` component for that.) Should we also hide the warning icon from them?

I've also asked about this in the [release criteria](https://docs.google.com/document/d/1EdEDcXoJmrryFYNc56zciuQ82G_iVGBQf1UFEkWiUtw/edit?disco=AAAA9gWEPvw).
</details>

**Comment by matthew-white** [comment]
Relatedly, I think we should hide the entity conflict summary box from project viewers. There's a [thread](https://docs.google.com/document/d/1EdEDcXoJmrryFYNc56zciuQ82G_iVGBQf1UFEkWiUtw/edit?disco=AAAA3SZlx-o) about this in the release criteria.

**Comment by matthew-white** [comment]
The release criteria has been updated with information about what a project viewer should and should not see. I'll update the title and description of this issue accordingly.

**Comment by dbemke** [comment]
**Tested with success!**
