### ISSUE TITLE
Unable to add entity label in later version of entity-updating form

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#552]
#### Steps to reproduce the problem

1. Author an XLSForm to update entities. Don't add a `label` column to the `entities` sheet.
2. Upload and publish the form in Central.
3. Update the XLSForm, adding a `label` column to the `entities` sheet.
4. Create a new draft for the form in Central, then attempt to upload the new version of the XLSForm.
5. Observe that there is an error message: "The form you have uploaded attempts to change the type of the field at /meta/entity. In a previous version, it had the type unknown. Please either return that field to its previous type, or rename the field so it lives at a new path."

I'm guessing that the new type is `structure`?

#### Expected behavior

It should be possible to add the `label` column to the `entities` sheet in a later version of the XLSForm.

#### Central version shown in version.txt

```
versions:
15e519a04eefc41049c30d53b6779682f7890764 (v2023.4.0-3-g15e519a)
+70acd3fecd1efb4c887f51447c0d6028e6eba88d client (v2023.4.0-36-g70acd3fe)
+bb6f38259d1cf842854fac8050731658f2ac5977 server (v2023.4.0-41-gbb6f3825)
```

#### Other notes (if any)

We should also check the reverse: is it possible to remove the `label` column of the `entities` sheet in a later version of the XLSForm? I'm guessing not and that that would be a change in field type from `structure` to `unknown`.

**Comment by matthew-white** [comment]
I'm wondering about the fact that the `meta/entity` field is initially of type `unknown`. Should we have it default to `structure` if it's `unknown`? The fact that it's `unknown` means that it's shown in the submissions table: #553. Though would there be downsides to having an empty `structure`?

**Comment by ktuite** [comment]
I came to a similar thought -- what if `entity` was always type `structure`? 

The [schema extraction code](https://github.com/getodk/central-backend/blob/master/lib/data/schema.js#L86-L95) has some entity-specific stuff in it, we could force `entity` to always be `structure` and maybe even force `label` to always be `string`. 

This type is stored in the database so we'd probably need to migrate entity + label types. 

On one hand, this feels kind of invasive. On the other hand, it seems annoying/fragile to work around these fields having potentially different types.
