### ISSUE TITLE
Summary box with conflicts after resolving the conflict in a different tab

### ISSUE THREAD

**Issue by dbemke** [getodk/central#555]
#### Problem description
If I can see the summary box with conflicts and in another tab I resolve the conflict (just by clicking the button - no edits). I go back to the summary box (in which I can still see the table with conflict) which I didn't refresh (to the resolved conflict) I edit the entity. Then I can see the edit in the table with conflicts.
#### URL of the page
https://staging.getodk.cloud/
#### Steps to reproduce the problem
Preconditions:
There is at an entity with a conflict on the server.
Steps:
1. Go to the entity with a conflict.
2. In the Data tab on the entities page click "More” on the entity with a conflict.
3. Leave the new tab (Entity detail page) opened and go back to the Data tab.
4. In the Data tab on the same entity with a conflict, click "Review parallel updates”.
5. In the dialog click "Show summary table” (don’t close the dialog).
6. Go to the Entity detail tab and click "Mark conflict as resolved” and confirm it.
7. Go to the second tab with the dialog with the summary box and click "Edit Entity”.
8. Edit some fields and click "Update”.
#### Screenshot
https://jam.dev/c/4796f628-b56b-4f3a-a37e-b1984cd1405b

#### Expected behavior
As mention in the PR #506 : The table shouldn't be shown in the modal if the conflict has been marked as resolved in another tab. A message should be shown about needing to refresh data.
#### Central version shown in version.txt
staging versions:
15e519a04eefc41049c30d53b6779682f7890764 (v2023.4.0-3-g15e519a)
+70acd3fecd1efb4c887f51447c0d6028e6eba88d client (v2023.4.0-36-g70acd3fe)
+bb6f38259d1cf842854fac8050731658f2ac5977 server (v2023.4.0-41-gbb6f3825)

#### Browser version
Chrome 119.0.6045.159 (64-bit), Firefox 120.0 (64-bit)

**Comment by matthew-white** [comment]
I think this was actually related to the [issue](https://github.com/getodk/central/issues/505#issuecomment-1838953240) about the last known good version. I'm not currently able to reproduce this issue, so I'm hoping it was resolved along with the other issue. @dbemke, would you mind checking whether this issue is resolved?

**Comment by dbemke** [comment]
The issue is fixed.
