### ISSUE TITLE
Entity detail page with the table of conflicts after resolving the conflict in a different tab

### ISSUE THREAD

**Issue by dbemke** [getodk/central#556]
#### Problem description
If I can see the table with conflicts in the Entity detail page and in another tab I resolve the conflict (just by clicking the button - no edits). I go back to the Entity detail page (in which I can still see the table with conflict) which I didn't refresh (to the resolved conflict) I edit the entity. Then I can see the edit in the table with conflicts.
#### URL of the page
https://staging.getodk.cloud/
#### Steps to reproduce the problem
Preconditions:
There is at an entity with a conflict on the server.
Steps:
1. Go to the entity with a conflict.
2. In the Data tab on the entities page click "More” on the entity with a conflict.
3. Leave the new tab (Entity detail page) opened and go back to the Data tab.
4. In the Data tab on the same entity with a conflict, click "Review parallel updates”.
5. In the dialog click "Show summary table” and click "Mark conflict as resolved” and close it .
6. Go to the Entity detail tab, edit some fields of the entity and click "Update”.

#### Screenshot
https://jam.dev/c/cf0c1725-e5e7-46e0-ad6a-b5eb9140a109

#### Expected behavior
As mention in the PR #506 : Needs discussion.
#### Central version shown in version.txt
staging versions:
15e519a04eefc41049c30d53b6779682f7890764 (v2023.4.0-3-g15e519a)
+70acd3fecd1efb4c887f51447c0d6028e6eba88d client (v2023.4.0-36-g70acd3fe)
+bb6f38259d1cf842854fac8050731658f2ac5977 server (v2023.4.0-41-gbb6f3825)

#### Browser version
Chrome 119.0.6045.159 (64-bit), Firefox 120.0 (64-bit)

**Comment by matthew-white** [comment]
This issue should be resolved now. When the feed is refreshed after the entity data is updated, the conflict summary box should no longer be shown, including the table. In the feed, you can see that the conflict has been resolved.

**Comment by dbemke** [comment]
**Tested with success!**

**Comment by srujner** [comment]
Tested with success!
