### ISSUE TITLE
Draft section is visible in all form views in a project

### ISSUE THREAD

**Issue by dbemke** [getodk/central#563]
#### Problem description
Draft section is visible in form views in a project so for example it’s possible start creating a draft and from this view go to Submissions
#### URL of the page
https://staging.getodk.cloud/
https://test.getodk.cloud/

#### Steps to reproduce the problem
1. Navigate to a form in a project.
2. Go to different tab (e.g. Submissions, Settings).
3. Try to create a draft from the chosen tab.
4. From Draft section go to e.g Submissions.

#### Screenshot
![draftinsubmisions](https://github.com/getodk/central/assets/56479916/31aad7d4-5819-4339-9f92-8ac62f125a54)

#### Expected behavior
Draft section shouldn’t be visible in other parts of form sections.
#### Central version shown in version.txt
staging versions:
versions:
c0bfac522d92a9224242f90a3e90df09f12ab540 (v2023.4.0-6-gc0bfac5)
+4b5d237c5d83f7fc5c64dce79229f9edd97cff62 client (v2023.4.0-46-g4b5d237c)
+38410ebe30f6082d9cebcd2e2bc9f38fbd07b4e2 server (v2023.4.0-48-g38410ebe)
test.cloud.getodk.org
versions:
65d38c5de66dc07245632a19f3458035337f1215 (v2023.4.0)
 95326b9ad66ec31c93bdb68c29f8797975d93fd2 client (v2023.4.0)
 63fdf150e1ed81e3b1059050f7b1ba323931ab24 server (v2023.4.0)

#### Browser version
Chrome 119.0.6045.159 (64-bit), Firefox 120.0 (64-bit)

**Comment by matthew-white** [comment]
I don't think we're planning to make changes here for .5, so I'm going to go ahead and close this issue for now. @dbemke, let me know if you think we should make any changes here, or if you have other thoughts about this issue.
