### ISSUE TITLE
OData entity schema missing version and conflict properties

### ISSUE THREAD

**Issue by ktuite** [getodk/central#565]
Bug noticed by QA:

"! DataSource.Error: Data: The property 'version' does not exist on
type 'org.opendatakit.entity.metadata'. Make sure to only use property names that are defined by the type or mark the type as open type."

* `version` and `conflict` need to be added

![Image](https://github.com/getodk/central/assets/76205/e36888fe-2ac2-4c49-9766-1d6a41bb6225)

**Comment by matthew-white** [comment]
It's also missing the `__system/conflict` property.

**Comment by matthew-white** [comment]
> `version` probably needs to be come `__version` in the `__system` object

I don't think the name of the property needs to change (it's already part of an `__` property). If it did change, then Frontend would have to change as well.
