### ISSUE TITLE
Create a new Entity List without publishing a Form

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#575]
See the story in the [release criteria](https://docs.google.com/document/d/1q_dY5JGy6rAYEv77C7zQvmvG6nErj1sw8LD9fVx6PDE/edit#heading=h.cafrdki6w16s).

**Comment by matthew-white** [comment]
@getodk/testers, this issue is now ready to be verified on the staging server. It isn't currently on test.getodk.cloud, but let me know if adding it there would be helpful for verifying bulk upload of entities (#589).

**Comment by dbemke** [comment]
I filed issue #624 (connected with creating new entities lists)

**Comment by srujner** [comment]
@matthew-white If possible it'll be helpful for us to have all of the newest changes on test.getodk.cloud also. Same with PR #576

**Comment by matthew-white** [comment]
Sounds good, @srujner! I'll include those changes the next time I update test.getodk.cloud. I'll let you know when I do that.

Thanks for filing those issues, @dbemke! If those are the only issues you encounter, I think it'd be OK to label this issue as verified. I think we'll try to fix those issues before release.

**Comment by srujner** [comment]
One small UI issue:
![Screenshot(66)](https://github.com/getodk/central/assets/85225519/5ed69421-9841-4930-901d-0c26d271eb5d)

**Comment by srujner** [comment]
@matthew-white @ktuite I've created a separate issue for the UI bug here: https://github.com/getodk/central/issues/630

**Comment by srujner** [comment]
Tested With Success!

**Comment by dbemke** [comment]
Tested With Success!
