### ISSUE TITLE
Add a new property to an Entity List without publishing a Form

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#576]
See the story in the [release criteria](https://docs.google.com/document/d/1q_dY5JGy6rAYEv77C7zQvmvG6nErj1sw8LD9fVx6PDE/edit#heading=h.9c8kyk5ohdxk).

**Comment by matthew-white** [comment]
@getodk/testers, this issue is now ready to be verified on the staging server. It isn't currently on test.getodk.cloud, but let me know if adding it there would be helpful for verifying bulk upload of entities (#589).

**Comment by dbemke** [comment]
I filed issue #626 (connected with creating new properties).

**Comment by matthew-white** [comment]
Thanks, @dbemke! If that's the only issue you encounter, I think it'd be OK to close this issue. I've added #626 to the project so that we can fix it before the release.

**Comment by srujner** [comment]
Error dialog is still visible after adding correct Entity Properties.

Steps to Reproduce:
- Open Add Entity Property dialog
- Provide incorrect name and click on the create button;
- Provide correct name and click on the create button;
- The dialog with incorrect name will still be visible.
![Screenshot(67)](https://github.com/getodk/central/assets/85225519/7871f682-cbcf-4a64-82ce-63a118130690)

**Comment by dbemke** [comment]
**Tested with success!**

**Comment by srujner** [comment]
**Tested with success!**
