### ISSUE TITLE
Central sets WORKER_COUNT based on host, not container resources

### ISSUE THREAD

**Issue by yanokwa** [getodk/central#577]
In https://github.com/getodk/central/blob/HEAD/files/service/scripts/start-odk.sh#L33 we set `WORKER_COUNT` based on total memory. 

According to https://forum.getodk.org/t/limiting-resources-memory-that-the-odk-central-service-can-consume/44357/2 that total memory is the host's memory not the container's memory, so you can have a situation where you are running Central in a memory limited container but using more workers than is recommended.

My guess is that most people don't allocate less than 1 GB, so this isn't urgent, but I wanted to document it.

**Comment by matthew-white** [comment]
It sounds like #588 fixes this issue. 🎉
