### ISSUE TITLE
Remove New! badge from Entities tab

### ISSUE THREAD

**Issue by lognaturel** [getodk/central#581]
The tab will be less new with v2024.1 so I think it's a good time to remove it so users don't start tuning out that badge.

@alyblenkin

**Comment by alyblenkin** [comment]
I agree; it's time to remove it! 

Documenting a few notes from our conversation earlier:
- We assume people will be getting updates through the "News" section in Central or the forum, so it should be OK for those who aren't frequently using Central and didn't see the badge. 
- To be validated by user interviews with lurkers (those who spend a lot of time on the forum, but don't participate)
- At one point we may want to explore updating the "News" section to draw more attention to it
