### ISSUE TITLE
See upload as the origin of an Entity

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#583]
See the story in the [release criteria](https://docs.google.com/document/d/1q_dY5JGy6rAYEv77C7zQvmvG6nErj1sw8LD9fVx6PDE/edit#heading=h.76qbjdp3ojzz).

**Comment by matthew-white** [comment]
@getodk/testers, the code for this story is complete, but it's not easy to test it yet. I think we should probably wait to test this story until #589 is complete. Once you're able to upload entities in bulk, it'll be easier to verify whether you can see the upload as the origin of an entity. Currently the only way to upload in bulk is via the API.

**Comment by dbemke** [comment]
We tried uploading a list of 400-500 entities, also 2 users doing it at the same time and on Chrome when the list is loading there's "Page Unresponsive" . It happened 27.03.2024 around 3p.m. CET


![Image](https://github.com/getodk/central/assets/56479916/04ddf06b-aa7e-4ff2-91d8-db8f111f2fa7)


**Steps to reproduce:**
1. Upload a file with entities e.g. https://test.getodk.cloud/#/projects/505/entity-lists/trees/entities


[trees.csv](https://github.com/getodk/central/files/14774030/trees.csv)
2. Scroll down the list of entities.

**Comment by matthew-white** [comment]
> Is there a specified number how many should load at once?

It starts out as 250, but once 1000 have been loaded, it starts loading 1000 each time.

> After that when I scroll up to see the top of the table there is only a table without any text

I've seen something like this when I've loaded many rows of a table. I'm a little surprised though that there's an issue as early as ~3,000 rows. We're planning to replace the infinite scroll here with pagination, which should help a lot with this sort of issue. Pagination would show fewer rows on the page at once.

> Page Unresponsive

This is probably a problem with the UI rather than the server, but I don't have many ideas about how to address it. 400–500 entities seems like a small number. I think the issue probably isn't related to there being two simultaneous users. Have you seen this issue before? Also, had you scrolled to the bottom of the table when this happened? Maybe like above, it's an issue with the UI trying to show too many rows at once.

**Comment by dbemke** [comment]
> This is probably a problem with the UI rather than the server, but I don't have many ideas about how to address it. 400–500 entities seems like a small number. I think the issue probably isn't related to there being two simultaneous users. Have you seen this issue before? Also, had you scrolled to the bottom of the table when this happened? Maybe like above, it's an issue with the UI trying to show too many rows at once.

The first time it happened I just uploaded 400 entities and scrolled to the bottom of the table. So probably it's connected with scrolling. When we tried adding at the same time+ scrolling my browser (Chrome) froze and needed restarting.

**Comment by srujner** [comment]
**Tested with success!**

**Comment by dbemke** [comment]
**Tested with success!**

**Comment by matthew-white** [comment]
> The first time it happened I just uploaded 400 entities and scrolled to the bottom of the table. So probably it's connected with scrolling. When we tried adding at the same time+ scrolling my browser (Chrome) froze and needed restarting.

Sorry @dbemke, I meant to ask more about this!

- Has it happened again that there's "Page Unresponsive" or Chrome freezes?
- Have you seen "Page Unresponsive" and/or Chrome freezing in the past? Or is it new?
- Do you see this only after you upload entities, or does it happen other times when you scroll? What happens if you scroll down that page without uploading entities?

**Comment by dbemke** [comment]
There was "page unresponsive" again but a short one. Steps in that case were:
1. An entity list without any entities added.
2. I clicked "Upload entities".
3. I downloaded the template and created around 400 entities in the file.
4. I uploaded the file.
5. Scrolled down the page
