### ISSUE TITLE
Delete an Entity from the Entity data table

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#584]
See the story in the [release criteria](https://docs.google.com/document/d/1q_dY5JGy6rAYEv77C7zQvmvG6nErj1sw8LD9fVx6PDE/edit#heading=h.w52sb1rrnr7v).

**Comment by srujner** [comment]
I found an issue with no auto refreshing the list number.
I've deleted rows 6th, 11th and 14th. 
The number of Entities in the "Download x Entities" button is correct, but I had to manually refresh the page so the list is sorted correctly without empty number.
![Screenshot(20)](https://github.com/getodk/central/assets/85225519/9d0dc5c7-376e-4c9e-b1c2-a271c20c39bb)

**Comment by dbemke** [comment]
After deleting and entity without refreshing the page the number in "Download x Entities" button is correct, but if download the CSV file there is a list of entities including also the deleted entity.

**Comment by matthew-white** [comment]
Thanks, @srujner and @dbemke!

> I found an issue with no auto refreshing the list number.

I've asked about this on Slack. :+1: I thought it'd help the user keep their place in the table if we didn't automatically update row numbers, but maybe it's unexpected.

> I had to manually refresh the page so the list is sorted correctly without empty number.

Are the row numbers also updated if you click the refresh button and don't refresh the page?

> if download the CSV file there is a list of entities including also the deleted entity.

That definitely sounds like a bug, though I think it's an existing one. I've filed an issue for it at getodk/central#599.

> I edited an entity so that the entity label contains new lines and the new lines are visible in the confirmation message after deleting it.

Hmm interesting. Right now, alerts like that always show new lines. That's because we need to show new lines in some cases, for example, showing some XLSForm errors. We could probably make it conditional though. In this case though, I think it's unlikely that a user would use a new line in an entity label. If they do, I think it's not terrible if they see the new line in alerts.

**Comment by srujner** [comment]
**Tested with Success!**

**Comment by dbemke** [comment]
**Tested with Success!**

**Comment by matthew-white** [comment]
> > I found an issue with no auto refreshing the list number.
> 
> I've asked about this on Slack.

For posterity, we decided in Slack not to update the row number for now. I wrote in Slack:

> I’m wondering how this should work given that the rows are reverse-ordered. We want to avoid a situation where the last row number isn’t 1, right? So if the row numbers start out as 3, 2, 1, and I delete row 2, then the row numbers should end up being 2, 1, not 3, 2, right?

We can see whether this ends up being an issue for users.
