### ISSUE TITLE
Display version number in web interface

### ISSUE THREAD

**Issue by issa-tseng** [getodk/central#59]
Per this comment: https://forum.opendatakit.org/t/odk-central-v0-4-setup-duplicate-default-server-error/17942/5 .

Put it somewhere nice and in an HTML comment (good for support requests). Although, it's also at /version.txt

**Comment by matthew-white** [comment]
@issa-tseng, now that the Frontend navbar has a help dropdown that links to /version.txt (getodk/central-frontend#398), is this issue ready to close?

**Comment by issa-tseng** [comment]
i think so.
