### ISSUE TITLE
Can we access App User QR Code using Central Api in getODK

### ISSUE THREAD

**Issue by nitesh047** [getodk/central#590]
I was working on getODK and wanted to create the app users using central API. Although I was able to create an app user using central API but I was wondering if we can access or generate the QR code of that user through API to collect the data.

Thanks in advance.

**Comment by matthew-white** [comment]
Hi @nitesh047! GitHub issues are used by the core team to plan and manage development work. Please post any questions or ideas on the [ODK Forum](https://forum.getodk.org) instead. Thank you!
