### ISSUE TITLE
Link from "API Access" button is incorrect

### ISSUE THREAD

**Issue by lognaturel** [getodk/central#604]
The "API Access" buttons above the data tables (submissions and entities) link to Apiary. We moved docs to https://docs.getodk.org a few months ago.

I was going to submit a PR to make the change but I thought we should discuss whether to keep this button. Given that no one has reported the issue, could it be that it's not accessed very often? It's not a 100% clear signal -- it's possible that people follow the links to the docs and are ending up where they need so don't see it as very important to report.

Anecdote: I have never used the button because when I want to do something API-related, I don't typically log into the frontend. I suspect that would be common. I only noticed it because I clicked on it when we were exploring ideas for the navigation updates.

**Comment by matthew-white** [comment]
It looks like we also link to Apiary from the "Analyze via OData" modal (if you click Other).
