### ISSUE TITLE
Form Attachments page does not show upload progress

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#606]
#### Problem description

While a form attachment is being uploaded from the Form Attachments page, a pop-up is shown that indicates what percent of the file has been sent. However, currently the percentage is always 0%.

#### Steps to reproduce the problem

1. Navigate to the Form Attachments page.
2. Upload a large file and/or [simulate a slow connection](https://developer.chrome.com/docs/devtools/network#throttle). Try something that keeps the pop-up visible for at least 10 seconds. I uploaded an 800 kB file while simulating slow 3G, and the upload took 15 seconds.
3. Observe that the percentage never changes: it is 0% throughout the upload.

#### Expected behavior

I expect the percentage to increase over the course of the upload.

#### Central version

I think this was introduced in v2023.5 when we updated axios (getodk/central-frontend#917).

**Comment by matthew-white** [comment]
@getodk/testers, this issue should now be fixed on staging.

**Comment by dbemke** [comment]
**Tested with success!**
