### ISSUE TITLE
Loading entity activity log is slow when server had many audit log entries

### ISSUE THREAD

**Issue by lognaturel** [getodk/central#618]
#### Problem description
Loading entity activity log is slow when server had many audit log entries

#### URL of the page
Example: https://test.getodk.cloud/#/projects/149/entity-lists/chairs/entities/468e873d-7181-4e17-8dce-2e4441669c11 -- the audits response takes 7.5s to start sending.

#### Steps to reproduce the problem
On a server with lots of audit log entries, navigate to a single entity details page.

#### Expected behavior
The entity details page should load quickly.

#### Central version shown in version.txt
```
versions:
645a8061b8df3644584cefc036d751c6115fcbec (v2023.5.1-3-g645a806)
+4e2dcf1035f1684f01a429d04267ede670ffee91 client (v2023.5.0-46-g4e2dcf10)
+85a0e3cbcec39c000d29002a9e9bce3150115ac2 server (v2023.5.0-35-g85a0e3cb)
```

#### Other notes (if any)
Almost certainly need to add an index for `sourceId` in audit details.

@getodk/testers you are almost certainly going to be annoyed by this, sorry!

**Comment by matthew-white** [comment]
getodk/central-backend#1116 was merged a while ago, but I just updated the QA server yesterday and took a look at the entity detail page today. Maybe things are a little faster than they were before, but I'm not sure that this issue has been fully resolved. It looks like the entity in the issue description has been deleted, but I tried out other entities in the same entity list, as well as other entity lists. The requests to &hellip;/audits and &hellip;/versions still usually take 5–6 seconds, and I've seen the requests take over 11 seconds. In contrast, the submission detail page loads pretty much immediately. I think it'd be worth looking into what part of the query is taking so long to run.
