### ISSUE TITLE
 while creating a dataset, the error informing about an invalid name of a dataset isn’t removed in the success dialog

### ISSUE THREAD

**Issue by dbemke** [getodk/central#624]
#### Problem description
While creating a dataset manually via "+New” button, the error informing about an invalid name of a dataset isn’t removed in  the success dialog (when a dataset has been created).
#### URL of the page
https://staging.getodk.cloud/
#### Steps to reproduce the problem
1. Navigate to Entities Lists page.
2. Click "+New” button.
3. Enter an invalid dataset name (e.g. 1234).
4. Click "Create”.
5. Enter a valid name.
6. Click "Create”.
#### Screenshot

![errorSuccess](https://github.com/getodk/central/assets/56479916/31dd3a24-6189-44a6-a26a-6cc050d8544e)

#### Expected behavior
The error should be removed after entering a valid name.
#### Central version shown in version.txt
https://staging.getodk.cloud/
versions:
f0b2a90bce34fc13b0df4affd8b3158d57bcf904 (v2023.5.1-5-gf0b2a90)
+2bb17a501416814bbd987ddc953abc5b0c40c58a client (v2023.5.0-43-g2bb17a50)
+267e0ad7806057fc82894f58bea680627f1de5cd server (v2023.5.0-49-g267e0ad7)

#### Browser version
Chrome and Firefox

**Comment by matthew-white** [comment]
Interesting! I don't think we account for this in other multistep modals either, e.g., the "Create App User" modal. But I guess the "Create App User" modal has more limited backend validation compared to this new modal: there are more restrictions on the name of an entity list. @ktuite, I'm thinking that we could probably get away with just calling `alert.blank()` after incrementing `step.value` in `DatasetNew`.

**Comment by srujner** [comment]
**Tested with Success!**

**Comment by dbemke** [comment]
**Tested with Success!**
