### ISSUE TITLE
UI Issue im the the Entity List dialog

### ISSUE THREAD

**Issue by srujner** [getodk/central#630]
**Problem description**

When you provide to long name for the Entity List the text will be outside of the dialog.

**Steps to reproduce the problem**

1. Navigate to the Entities tab
2. Click on the New button next to the Entity Lists
3. Provide very long text and click on the Create button;
4. The success message will be shown with text outside the dialog box.
![Screenshot(66)](https://github.com/getodk/central/assets/85225519/f532dec3-ea6a-479c-887d-df0a7d6ca1ea)

**Expected behavior**
Text should fit within the dialog box

**Comment by matthew-white** [comment]
Copied from https://github.com/getodk/central/issues/575#issuecomment-2047858934:

> @ktuite, I'm thinking that we should specify `overflow-wrap: break-word;`, but not just for this one paragraph. What do you think about specifying that in the `text-block` mixin?

**Comment by srujner** [comment]
**Tested with Success!**

**Comment by dbemke** [comment]
**Tested with Success!**
