### ISSUE TITLE
Add text to Create Entity List modal if project is encrypted

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#631]
If a project is encrypted, then incoming submissions won't modify entities. Yet entities can still be useful in encrypted projects. @lognaturel wrote on Slack:

> You could use entities **as long as they’re not manipulated by forms**
> So you could do something like upload a list of districts that’s shared between forms and managed entirely in Central or through the API
> There is a reasonable use case for entities in projects with submission encryption.

In the "Create Entity List" modal, it'd be useful to mention something along these lines if the project is encrypted (i.e., if its `keyId` property is not `null`). The user should be able to create an entity list, but it should also be clear that new submissions won't create or update entities. That fact about submissions is [mentioned](https://github.com/getodk/central-frontend/blob/2bb17a501416814bbd987ddc953abc5b0c40c58a/src/components/project/enable-encryption.vue#L289) in the "Enable Encryption" modal, but a reminder would be helpful.

**Comment by dbemke** [comment]
**Tested with success!**

**Comment by srujner** [comment]
Tested with success!
