### ISSUE TITLE
After uploading entities the user can't see the whole "Data to import" part if the list is long

### ISSUE THREAD

**Issue by dbemke** [getodk/central#639]
#### Problem description
In the Import Data from File modal if the Data import part is moved to the bottom of the page (because of a long list of entities) after uploading entities the user isn’t moved to the bottom of the list/modal – the popup box and the "Append data" button aren't visible so the user doesn't know that so action needs to be taken.
#### URL of the page
https://test.getodk.cloud/#/projects/385/entity-lists/trees/entities
#### Steps to reproduce the problem
1. Navigate to the Entity lists page to the Data tab with a list of at least 50 entities (e.g. the URL above).
2. Click "Upload”.
3. Change the number of entities shown per page to 50.
4. Scroll down so that the "Choose one” button is at the bottom of the page.
5. Click "choose one” and upload a file with a few entities (or drag the file).
#### Screenshot

https://jam.dev/c/84fb0f6e-2961-45b1-beb7-c29636511ac2

#### Expected behavior
After uploading entities the user should see the whole "Data to import" part.
#### Central version shown in version.txt
https://test.getodk.cloud/
versions:
9a9ec7c034de07e990c9c408ca768326e2154c96 (v2023.5.1-10-g9a9ec7c)
+2f169138bbaecc1b48667a1eb6db40440416dc00 client (v2023.5.0-59-g2f169138)
+60ac8ca5307ff01a151180d5241a8e17a223885e server (v2023.5.0-55-g60ac8ca5)
https://staging.getodk.cloud/
versions:
9a9ec7c034de07e990c9c408ca768326e2154c96 (v2023.5.1-10-g9a9ec7c)
+82438aa97dcd305aac7973736016163a963b95c2 client (v2023.5.0-54-g82438aa9)
+60ac8ca5307ff01a151180d5241a8e17a223885e server (v2023.5.0-55-g60ac8ca5)

#### Browser
Chrome, Firefox

**Comment by srujner** [comment]
**Tested with Success!**

**Comment by dbemke** [comment]
**Tested with Success!**
