### ISSUE TITLE
Content-Type header missing in some responses

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#660]
#### Problem description

When I load the homepage, I see that some responses don't have a `Content-Type` header. That includes:

- index.html
- version.txt
- Most JSON responses from Backend
  - When I navigate to the Submissions page, I see that OData JSON does come with a header.
  - Problem responses also seem to come with a header. You can see that by navigating to a form without a draft, which will lead to a 404 response.

#### URL of the page

https://staging.getodk.cloud/#/

#### Steps to reproduce the problem

- Navigate to the page.
- Open the Network tab of Chrome devtools.
- Refresh the page.

#### Expected behavior

I expected to see a `Content-Type` header for every response. We return `nosniff` for the `X-Content-Type-Options` header, which to me signals that we intended to return `Content-Type`.

#### Central version shown in version.txt

```
versions:
42d83f19b30d638aae871243bce2caa0d8c6095d (v2024.1.0-1-g42d83f1)
+ed5162b5b46e0e19602b062ec7dc2bf7af99e8a8 client (v2024.1.0-2-ged5162b5)
+21582a04abd56831c51d7aa990b7413d7830938a server (v2024.1.0-2-g21582a04)
```

**Comment by yanokwa** [comment]
@matthew-white Is this a new problem in v2024.1? Or something that has always been there?

**Comment by matthew-white** [comment]
I'm not completely sure, and the answer could also be "both." For index.html and version.txt, I assume that we've never returned `Content-Type`. We're relying on nginx to add `Content-Type` for those files, but it's not. However, for the JSON responses from Backend, it's possible that that changed with v2024.1. I see that getodk/central-backend#1110 made changes in this area. But it's also possible that it's always been an issue for Backend.

**Comment by matthew-white** [comment]
Happy to report a false alarm here! It turns out the `Content-Type` header was missing because the responses were 304s. When I disable cache in Chrome devtools, I see `Content-Type` come through for all responses on the homepage. I think it's expected that `Content-Type` is missing for a 304.
