### ISSUE TITLE
Delete submissions via API

### ISSUE THREAD

**Issue by ktuite** [getodk/central#667]
* Delete single submissions (via API ~and frontend~)
* Soft-delete (put in trash) for 30 days
* Purge after 30 days

Submissions can have attached files and client audit files.
Things that link to submissions (including entities) can already handle deleted submissions (when entire form is deleted).

**Comment by matthew-white** [comment]
I've updated the issue title and description to make it clear that this issue for v2024.2 is just for deleting submissions via API. We also want to support submission deletion from the Frontend, and I've filed a separate issue for that: #709.
