### ISSUE TITLE
Add hover cards

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#670]
See the story in the [release criteria](https://docs.google.com/document/d/1sjAB68yy17Aw0gu5UYtAuadlg8mftsEJmVJD3el54QI/edit#heading=h.9v7b2av6wcqx).

**Comment by dbemke** [comment]
Is the geometry (property) in the correct format (numbers...numbers)?
![Image](https://github.com/user-attachments/assets/3150c911-202f-42a7-ba05-87dd6310687a)

**Comment by srujner** [comment]
Some form names are cut off in the Firefox browser
![bug1](https://github.com/user-attachments/assets/3cae96ba-88a9-4579-a07e-579f25e9775c)

**Comment by matthew-white** [comment]
Thank you, those both look like issues. :+1: I've also noticed that in some cases, there is too much padding below the list of properties in the hover card for an entity list. For example, if you hover over the "basic" entity list here: https://test.getodk.cloud/#/projects/414/entity-lists

<img width="296" src="https://github.com/user-attachments/assets/bd9c8b30-6666-44a3-9572-6dd6c11c6aa0">

**Comment by matthew-white** [comment]
I didn't have a chance to make these changes today, but I'll do so soon.

**Comment by srujner** [comment]
Hey, shouldn't the Infocard be visible also on that page after hovering the mouse over any of the links?
![Screenshot(216)](https://github.com/user-attachments/assets/c23208b5-0819-420d-81bd-369b92e32163)

**Comment by matthew-white** [comment]
> shouldn't the Infocard be visible also on that page after hovering the mouse over any of the links?

This should now be fixed.

**Comment by matthew-white** [comment]
@sadiqkhoja mentioned to me yesterday that he was seeing an issue with hover cards:

> Forms with lengthy names show the card outside of the screen

In other words, if there wasn't enough space for the hover card on either the right or the left of the link, it was being shown partly offscreen. Instead, we want to show the hover card above or below the link if there isn't space for it on the right or left.

getodk/central-frontend#1097 was merged to address this issue, and the issue should now be fixed. Let me know if you ever notice a hover card being shown offscreen.

![](https://github.com/user-attachments/assets/d002a6c4-f7b4-4dfb-a093-39452980d48c)

**Comment by matthew-white** [comment]
We're also tracking another issue with hover cards. It definitely affects hover cards for forms and may affect other hover cards as well. The issue is: In a hover card for a form, if the text in the second column is shorter than the text in the first column (i.e., if the form version is short), then the hover card will widen to fit the full width of the form name. The problem is that hover cards are not supposed to become arbitrarily wide. The form name is supposed to truncate if it's too long. I'm planning to fix this issue tomorrow.

**Comment by matthew-white** [comment]
> hover cards are not supposed to become arbitrarily wide. The form name is supposed to truncate if it's too long.

This should now be fixed.

> Is the geometry (property) in the correct format (numbers...numbers)?

> Some form names are cut off in the Firefox browser

I think these are the last two things that need to be fixed.

**Comment by dbemke** [comment]
Is the long property name already fixed- should it be "bbbbb..."?
![Image](https://github.com/user-attachments/assets/e83dccac-5b59-42e5-802d-250f91d1f840)

**Comment by matthew-white** [comment]
> Is the long property name already fixed- should it be "bbbbb..."?

That one is actually by design. If the list of properties doesn't fit, it will be visible up until the very edge of the hover card. In the release criteria, there's a screenshot along those lines that you can see.

> Is the geometry (property) in the correct format (numbers...numbers)?

This should now be fixed. I haven't updated the QA server yet, but you can see the fix on staging. I'll update the QA server soon as well.

> Some form names are cut off in the Firefox browser

I actually wasn't able to reproduce this issue on my machine, perhaps due to differences in fonts. However, I made some changes that I'm hoping has addressed this. That change can be seen on staging.

> I've also noticed that in some cases, there is too much padding below the list of properties in the hover card for an entity list.

This should now be fixed on staging. The issue was due to property names that contained a hyphen.

**Comment by dbemke** [comment]
I'm not sure about this case- it feels ok but on the other hand there are 2 different values. When the user is on the page with entity lists and a new entity is created (while being on the page), the hover card shows the newest number of entities (10) while the page (which wasn't refreshed) shows the number of entities without the newly created entity (9). Should I file an issue or it's ok?
![Image](https://github.com/user-attachments/assets/ef8ea890-cb64-4ebc-98ee-a930dfe32cff)

**Comment by dbemke** [comment]
After editing an entity with a long name, the hover card in submission detail page is broken (wrong width of property name, entered values are show beyond the hover card.
https://staging.getodk.cloud/#/projects/97/forms/trees_registration/submissions/uuid%3A2d68092f-0d00-4123-b98a-b87f8c19f9f8
![Image](https://github.com/user-attachments/assets/8b57cdac-a302-457f-8f03-0e6a30a7c4e6)

**Steps to reproduce:**
1. Go to the Entities "Data” tab.
https://staging.getodk.cloud/#/projects/97/entity-lists/trees/entities
2. Click "More”.
3. In the detail page click "Edit”.
4. In e.g. circumference_cm field enter a long name/number and update the entity.
5. In the "Activity” part click the hyperlink to the submission.
6.  Hover over the "Created entity” hyperlink.

**Comment by matthew-white** [comment]
> I'm not sure about this case- it feels ok but on the other hand there are 2 different values. When the user is on the page with entity lists and a new entity is created (while being on the page), the hover card shows the newest number of entities (10) while the page (which wasn't refreshed) shows the number of entities without the newly created entity (9). Should I file an issue or it's ok?

I personally think it's OK. Maybe it's even a good thing, as it's a signal that the page is out-of-date. This question also came up during code review, and I wrote some comments about it [here](https://github.com/getodk/central-frontend/pull/1067#issuecomment-2530194370).

> After editing an entity with a long name, the hover card in submission detail page is broken (wrong width of property name, entered values are show beyond the hover card.

I was able to reproduce this, and we should have a fix ready soon. Since we put out the release yesterday, I filed a new issue to track this bug: #854.

**Comment by dbemke** [comment]
**Tested with success!**
