### ISSUE TITLE
Add counts and other labels to more nav tabs

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#671]
See the story in the [release criteria](https://docs.google.com/document/d/1SXQjHFfOL4q2_5rOd0stLq3FGHnzJPJNv6VECfVkwLw/edit#heading=h.ivr9e2ra2rws).

**Comment by matthew-white** [comment]
We may make some styling changes to the nav tabs and/or the new counts, but nothing big. I think that can come in a separate PR, and we can go ahead and close this issue.

**Comment by matthew-white** [comment]
@getodk/testers, this issue is now ready to be verified on the staging server.

**Comment by dbemke** [comment]
The number in Forms tab counts only published forms? Drafts aren't included.

**Comment by dbemke** [comment]
Does inactive in the Public access tab mean with revoked access? I revoked access to links and the number is still visible in the tab. Should I file an issue?


![Image](https://github.com/user-attachments/assets/862639af-00f7-40c8-ab68-42dbb82e370a)

**Comment by matthew-white** [comment]
> The number in Forms tab counts drafts and published forms?

Yes, the number in the Forms tab should match the number of rows in the table below. For some user roles, we don't show certain forms in the table, and in that case, the number in the tab should still match the number of rows that the user can see (it should similarly not include the hidden forms). A Data Collector user can't see draft forms, and a Project Viewer can't see closing forms.

Forms in the trash should not be included in the number in the tab.

> Does inactive in the Public access tab mean with revoked access?

Yes, exactly.

> I revoked access to links and the number is still visible in the tab.

Ah I think that was a bug. It should be fixed now on staging.

**Comment by srujner** [comment]
**Tested with Success!**

**Comment by dbemke** [comment]
**Tested with Success!**
