### ISSUE TITLE
Adding magenta outline to feedback button

### ISSUE THREAD

**Issue by alyblenkin** [getodk/central#673]
This is a very small thing that doesn't need to be prioritize straight away but I wanted to capture a few ways to improve it:

- Add magenta outline
- Bump it up so it's not so low on the page

**Comment by matthew-white** [comment]
How far up should we bump the button? Currently it's 100px from the bottom of the window.

**Comment by alyblenkin** [comment]
@matthew-white Maybe 500px from the bottom? I don't think that shouldn't disrupt the other pages. I also don't want it to overlap with the summary section on the landing page.
