### ISSUE TITLE
Redesign breadcrumbs

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#674]
See the story in the [release criteria](https://docs.google.com/document/d/1sjAB68yy17Aw0gu5UYtAuadlg8mftsEJmVJD3el54QI/edit#heading=h.7tqxj4ou7444).

**Comment by srujner** [comment]
the space between the texts could be a little bigger (more centered) and it looks like it was in the Release criteria
![Screenshot(201)](https://github.com/user-attachments/assets/99548feb-7b7e-4ed9-9529-680a99d268c5)

**Comment by srujner** [comment]
Long Project name can break the breadcrumb:
![Screenshot(204)](https://github.com/user-attachments/assets/a39fcc53-befa-4b77-ad37-6c2c6add4791)

**Comment by srujner** [comment]
@matthew-white @ktuite 
should above small issues wait to be resolved here or should I filled it as separate ones and close this pr?

**Comment by ktuite** [comment]
I'll track it in a new issue so it doesn't get lost! https://github.com/getodk/central/issues/834

**Comment by matthew-white** [comment]
@srujner, I think both points should be addressed now on the server. Would you mind taking another look?

**Comment by srujner** [comment]
Looking good, closing the pr ;)
