### ISSUE TITLE
Update frontend to show more information about offline branches

### ISSUE THREAD

**Issue by ktuite** [getodk/central#683]
Update frontend to show more information about offline branches, especially when involved in conflicts or when there is no single entity version on the server that exactly represents what the data collector saw (the "author's view").

Note that Collect will likely generate/provide branchIds and trunkVersions for _all_ entities so there needs to be a way of checking that a branch has multiple actions in it before labeling it as an offline branch/action.

**Comment by matthew-white** [comment]
I'm about to wrap up getodk/central-frontend#1020, so I'm going to go ahead and close this issue.
