### ISSUE TITLE
When a draft form creating an entity list is discarded, the entity properties for the draft entity list block creation of those properties in a real entity list

### ISSUE THREAD

**Issue by lognaturel** [getodk/central#695]
#### Problem description
I tried to add properties to an Entity List I created through the frontend that has 0 properties and got an error saying the property already existed.

#### URL of the page
https://test.getodk.cloud/#/projects/542/entity-lists/suspected_afp_cases

#### Steps to reproduce the problem
1. Upload a form draft that creates an entity list
2. Discard the draft
3. Create an entity list with the same name
4. Try to add properties of the name that would have been created, you can't

#### Screenshot
<img width="992" alt="Screenshot 2024-08-22 at 4 59 46 PM" src="https://github.com/user-attachments/assets/3e15e111-fe3d-4cd7-9f1e-c4ef0136459a">

#### Expected behavior
No comparison against properties in draft entity lists

#### Central version shown in version.txt
```
f21b33acc8dae215e54485849e7dd59167e6f433 (v2024.1.0)
 3fb0c22b1cbdc3a6004963afcc3847a82c09307d client (v2024.1.0)
 b4754cf52bfa64b1ca841bc9ccb64a38726398e8 server (v2024.1.0)
```

#### Browser version
Firefox

#### Around when did you see the problem (in UTC)?
12:00 AM
Friday, August 23, 2024

**Comment by lognaturel** [comment]
Oh! I think I might have created a draft with that Entity List previously but then discarded the draft.

**Comment by srujner** [comment]
**Tested With Success!**

Issue is no longer reproducing
