### ISSUE TITLE
Entity submission backlog: apply create as update

### ISSUE THREAD

**Issue by ktuite** [getodk/central#702]
This other issue https://github.com/getodk/central/issues/682 captured the main cases of force-applying submissions held in the backlog. An update could be applied without the right base version, and an update about a non-existent entity that appeared to be created offline could be applied as a create.

These didn't cover the case where a missing offline create comes in _after_ an update was force-applied as a create. In this case, we need to apply the create as an update.

**Comment by dbemke** [comment]
**Tested with success!**

**Comment by WKobus** [comment]
Tested with Success!
