### ISSUE TITLE
Delete Submissions from UI

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#709]
As of v2024.2, submission deletion is possible via the API (#667). Submissions will be purged after 30 days. We also want to add submission deletion to Frontend, which is what this issue is for.

We support _entity_ deletion in Frontend, and we can probably adapt that same code for submission deletion. There are some details to consider, for example, after an entity is deleted, the entity count is updated. We support entity deletion from the entities table and from the entity detail page, and I think it'd be nice to similarly be able to delete a submission from either the submissions table or the submission detail page.

We don't yet support listing deleted entities or restoring/undeleting them, but we will want to be able to list and (I think) also restore deleted submissions from Frontend. To do so, we'll need to make a Backend change so that it's possible to retrieve the list of deleted submissions (something like the `?deleted=true` flag that we support for the forms endpoint).

There is a related mockup in the [release criteria](https://docs.google.com/document/d/1sjAB68yy17Aw0gu5UYtAuadlg8mftsEJmVJD3el54QI/edit#heading=h.tn2dyphlu9a2) for v2024.3. There are also some old notes from the [block 14](https://docs.google.com/document/d/1kpU2uIGYKOYQqfqgP4K40TjE_g3Ic-moWn-jn_7rEcg/edit#heading=h.rtyzownkn1l0) release criteria (under Later Release). Submission deletion has been discussed on the forum, for example, [here](https://forum.getodk.org/t/delete-individual-submissions/39200).

Here's an idea that was in the parking lot that I'm not sure is captured elsewhere:

> there will be some language on the projects table (or maybe an activity feed) showing that there are pending deleted submissions.

**Comment by matthew-white** [comment]
> we'll need to make a Backend change so that it's possible to retrieve the list of deleted submissions (something like the `?deleted=true` flag that we support for the forms endpoint).

I think we should probably add something like the `?deleted=true` flag to the REST API endpoint to list submissions. But Frontend actually doesn't use that endpoint: it uses OData instead. We'll need to modify the OData endpoint so that it can return deleted submissions. As part of that, we'll need to return `deletedAt` under `__system`. I think we should also include a `deletedAt` property in the OData schema/metadata. (Should we include it in the schema all the time or only when deleted submissions are requested?)

**Comment by issa-tseng** [comment]
suggested css adjustments:

``` css
.toggle-deleted-submissions {
  margin-left: 8px;    // up from 5
  .icon-close { margin-left: 3px; } // up from 0
}
.purge-description {
  left: 12px; // up from 5
}
```

otherwise it seems like it works great!

**Comment by matthew-white** [comment]
Thanks, @issa-tseng! I have a PR up for these changes here: #1055.

**Comment by dbemke** [comment]
Should it be possible to view or download media from a deleted submission?

**Steps to reproduce:**
1. In All widgets form attach media files.
2. Delete the submission.
3. Go to the deleted Submissions and try to view or download the media. (there's 404.1 error)
![Image](https://github.com/user-attachments/assets/90f29347-ec6d-4aad-b702-32ff618e949f)
![Image](https://github.com/user-attachments/assets/bc91ce3b-2859-4bba-b132-abf89d982656)

**Comment by sadiqkhoja** [comment]
Good catch! I don't think it should be possible. I will make the change

**Comment by dbemke** [comment]
**Tested with success!**

**Comment by WKobus** [comment]
**Tested with success!**
