### ISSUE TITLE
Entity List template CSV gets opened and saved by Excel as not UTF-8

### ISSUE THREAD

**Issue by lognaturel** [getodk/central#721]
#### Steps to reproduce the problem
1. Download an Entity List template CSV
2. Double click to open in Excel
3. Populate a cell with non-ASCII characters (e.g. Hélène)
4. Save from Excel
5. Upload the Entity List CSV

#### Screenshot
<img width="656" alt="Screenshot 2024-09-25 at 12 15 04 PM" src="https://github.com/user-attachments/assets/14453c01-5dcc-4c36-9475-9f4c27400d23">

#### Expected behavior
Excel opens and saves the file as UTF-8

#### Central version shown in version.txt
```
versions:
67bd0ad3def294a89fc17a8be8e1001a37303f80 (v2024.1.0-15-g67bd0ad)
+3372015d4fe4ba34598ab5e4552c1ec1e11ee205 client (v2024.1.0-41-g3372015d)
 3ae8a69011f3839b60ecc9fdda770faa408d16d4 server (v2024.1.0-35-g3ae8a690)
```

#### Other notes (if any)
This is related to https://github.com/getodk/central/issues/752. I think that in this case we can add the BOM because this template exists just to make it easier to input data. We generally don't expect the template to be ingested into data pipelines or edited by scripts.

**Comment by srujner** [comment]
I tried to reproduce this error, but I have the same problem, which I think has been in the past with Libre Office on ubuntu. 
I saved the file as UTF-8 and when trying to upload it to central i get this error:
![Screenshot2](https://github.com/user-attachments/assets/254c4256-50bc-4457-b72b-2fb795dc55d9)
Excel saves file with semicolon instead of comma.

I have Excel version from 2007

**Comment by sadiqkhoja** [comment]
Can you please share the file saved by Libre Office.

For Excel, I think your system "List separator" setting is `;` or Excel decimal separator is `,`. 

List separator in windows:

- Click the Start button and then Control Panel
- Open the dialog box for changing Regional and Language settings
- Find the List separator setting
- Enter `,`

Decimal and thousands separator in Excel:

- File > Options > Advanced
- Set decimal separator to `.` and thousands separator to `,`

More details: https://www.ablebits.com/office-addins-blog/change-excel-csv-delimiter/

**Comment by srujner** [comment]
@sadiqkhoja The instruction was helpful, now everything is saved correctly. 

But is this fix available on staging? 
I was able to reproduce the case from @lognaturel and also other cases with polish signs:
![Screenshot2(1)](https://github.com/user-attachments/assets/d48a129e-6cc8-49c2-8772-2bec75edc570)
[colors6.csv](https://github.com/user-attachments/files/18005704/colors6.csv)

I also see that my version of staging is different:
versions:
51a3e10fdf188473ce38b24313962c674188c9ff (v2024.2.1-4-g51a3e10)
+ba422a03b6ec987536f1c4d8388d09e8f0ce67b3 client (v2024.2.1-39-gba422a03)
+663e3b9e0c0f2bc10037d3a83f951494b4e27b64 server (v2024.2.0-97-g663e3b9e)

**Comment by sadiqkhoja** [comment]
The file `colors6.csv` doesn't have BOM character in it. I am wondering how that file was created/edited.

On a separate note semi-colon separated CSV file is parsed and uploaded correctly. File attached.
[colors 20241204113146.csv](https://github.com/user-attachments/files/18012188/colors.20241204113146.csv)

@srujner I would like to do a sync session with you to see what's happening. Sent you an email invite.

**Comment by srujner** [comment]
@sadiqkhoja I accepted the meeting
