### ISSUE TITLE
Warn about forms with old version of entity spec <2024.*

### ISSUE THREAD

**Issue by ktuite** [getodk/central#730]
When we [migrate the entity form spec in existing entity forms](https://github.com/getodk/central/issues/692) we will ~not want to accept~ want to warn about _new_ forms with an _old_ entity spec. 

From the above issue:

> Once forms are migrated, we will need to check going forward that all form definitions that are uploaded (for new or existing forms) are capable of making offline changes. Specifically, we should reject form definitions that specify an entities spec before 2024.1. That shouldn't be an issue for users using XLSForms (things should work seamlessly), because pyxform will automatically specify 2024.1.

**UPDATE:** The issue mentioned rejecting form definitions, but we've decided to show a warning about them instead.

One hurdle users might encounter is if they have an old version of their form in XML and it has an old entity spec version. In that case, we can give users info on how to recover (e.g. download upgraded XML, look at spec to figure out changes to apply).

**Comment by matthew-white** [comment]
We've discussed that it'd be nice not to outright reject forms like this if doing so is not necessary. Instead, we can warn users if the form definition they've uploaded specifies an old spec. I'll update the description above.

Surfacing the warning in Frontend will probably require changes to Frontend. I've added the frontend label to the issue.

I've also removed the documentation label, since it isn't a docs issue. There's an issue at getodk/docs#1855 to update user docs, and an issue at getodk/central-backend#1211 to update API docs. Feel free to edit those!

**Comment by dbemke** [comment]
I'm not sure if this case works as expected - when I upload an old spec entity form which exists in the project first there's the dialog with information about the old spec (I tap "Upload anyway") and then the dialog with  information that the form exists in a project appears. Should the dialog informing that the form already exists in the project be the first (and only) one?
![Image](https://github.com/user-attachments/assets/4268ea42-eb08-4ec4-88d6-5385e22b23ff)
![Image](https://github.com/user-attachments/assets/abeac8cc-0d8d-49a2-a3c1-425e3c354aeb)


**Steps to reproduce:**
1. Upload an old spec entity form and publish it.
2. Try to add the same form again.
3. The dialog with information about the spec appears, tap "Upload anyway"

**Comment by ktuite** [comment]
It probably should warn when they upload a new version. (And it probably doesn't do that right now, does it? I can add that!)

> Should the warning about the old spec appear only when a user adds a new or also when adds a new version of a form (e.g changing the new spec to the old spec), undeletes the old spec form?


Hmm, I see what you're saying with these two phases of dialog boxes. Knowing how it works under the hood, there isn't really a way to do something different. The first one about the version is a warning and the second is an error even though they are about different things.

> I'm not sure if this case works as expected - when I upload an old spec entity form which exists in the project first there's the dialog with information about the old spec (I tap "Upload anyway") and then the dialog with information that the form exists in a project appears. Should the dialog informing that the form already exists in the project be the first (and only) one?

**Comment by dbemke** [comment]
> It probably should warn when they upload a new version. (And it probably doesn't do that right now, does it? I can add that!)

The warning doesn't appear when a new version of a form is uploaded. 
We finished testing. Should we wait for changes with the warning while adding a new version or is it going to be a separate issue?

**Comment by ktuite** [comment]
Actually, we've decided to close the new #816 issue -- it requires too much of a code change to justify. You can evaluate this issue with just the functionality for *new* forms. Thanks!

**Comment by dbemke** [comment]
**Tested with success!**

**Comment by WKobus** [comment]
**Tested with success!**
