### ISSUE TITLE
Add TEMPORARY label to form draft QR code

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#746]
This issue is to add the word TEMPORARY in the middle of the form draft QR code. See the [release criteria](https://docs.google.com/document/d/1sjAB68yy17Aw0gu5UYtAuadlg8mftsEJmVJD3el54QI/edit#bookmark=id.iem9ly4hqk39) for details and a screenshot. I thought we could separate this change from the rest of #728.

**Comment by matthew-white** [comment]
@ktuite, is this something you think you could help with? 🙏 It would come after I finish the rest of #728. I can help with any Vue shenanigans.

**Comment by matthew-white** [comment]
@getodk/testers, this issue is now ready for testing on the staging server. It's part of a larger story about redesigning form drafts and adding a new "Edit Form" page. Eventually these changes will appear on that "Edit Form" page. However, the changes can be seen today on the existing Testing page. I think it'd be OK to go ahead and verify the changes there now.

**Comment by srujner** [comment]
**Tested with Success!**

**Comment by srujner** [comment]
**Tested with Success!**

**Comment by matthew-white** [comment]
> I thought we could separate this change from the rest of #728.

Just to make the status of things clear, I wanted to note that #728 has been bumped to v2025.1, but we will ship the change for this issue in v2024.3. This issue goes along with other changes that we'll make to the buttons above Draft test Submissions: #833. We'll ship #833 in v2024.3. Like this issue, #833 has been pulled out of #728.
