### ISSUE TITLE
Can't see test Submissions if filters are selected in Submissions tab

### ISSUE THREAD

**Issue by sadiqkhoja** [getodk/central#756]
#### Problem description

If any filters are selected in the main Submissions tab then on the Testing tab no test Submissions are shown

#### URL of the page

On test server `/projects/473/forms/BFHI_ODK_primary_v2.0/draft/testing`

#### Steps to reproduce the problem

- Open any published Form which has a draft version and some test Submissions as well. On test server you can use `/projects/473/forms/BFHI_ODK_primary_v2.0/draft/testing`
- Go to Testing tab, you will see the testing Submissions
- Go to Submission tab, select any filters, I have been selecting 'Edited' from the review state dropdown.
- Go back to the Testing tab, now no Submission is visible. In the console, I see an error `TypeError: Cannot read properties of null (reading 'abort')` 

#### Screenshot
![image](https://github.com/user-attachments/assets/b174740c-018f-43db-bd81-bc4b9aa877a6)

#### Expected behavior

Filters on Submissions tab should not have any effects on testing Submissions

#### Central version shown in version.txt

```
2d95a612218e7c73ee8b3e715749401f08fc00ac (v2024.2.1-1-g2d95a61)
 99b11a8cc7d30dbc03376f97ab345dc0d18c2a98 client (v2024.2.1)
+d2054f4d901a548296514f2807a85520ec69f34c server (v2024.2.0-28-gd2054f4d)
```

#### Browser version

Chrome 129.0.6668.103 (Official Build) (arm64)

#### Around when did you see the problem (in UTC)?

2024-10-18 7:00 PM

#### Other notes (if any)

Error message and stack trace in the console:

```
TypeError: Cannot read properties of null (reading 'abort')
    at Proxy.cancelRequest (resource.js:67:71)
    at Proxy.request (resource.js:203:37)
    at Proxy.fetchChunk (list.vue:254:18)
    at Proxy.fetchData (list.vue:293:12)
    at Proxy.created (list.vue:239:10)
    at a (runtime-core.esm-bundler.js:158:32)
    at l (runtime-core.esm-bundler.js:166:17)
    at Wt (runtime-core.esm-bundler.js:3509:3)
    at Ut (runtime-core.esm-bundler.js:3427:5)
    at qr (runtime-core.esm-bundler.js:7341:5)
```

**Comment by matthew-white** [comment]
This fix is now available on the staging server. It'd be good to verify that the behavior described above cannot be reproduced.

@sadiqkhoja also noted on the PR:

> Any page that have filters like Entities data and System audit should be tested as well for regressions.

I ended up thinking that the change in the PR was low-risk, which is why I merged it after regression testing was complete. The code change is pretty small and isolated. However, I do think it'd be a good idea to do some limited testing of filters. I think it'd be OK to focus that testing on the submissions page.

**Comment by dbemke** [comment]
I don't know if it's connected ?- I just tried to reproduce the steps mentioned in the issue: a form with a draft version-in submission tab I changed filters (refreshed the page), clicked "Testing" tab and refreshed the page (the were testing submissions) and I got an error.
https://staging.getodk.cloud/#/projects/101/forms/all-widgets/draft/testing
![Image](https://github.com/user-attachments/assets/0102a525-4fcc-4b14-9444-a0859ac5e90d)

**Comment by matthew-white** [comment]
I would think that it's not connected. It sounds like an intermittent network error. You should only see the "Error Loading Central" page if one of the basic parts of the UI fails to load (client-config.json). From looking at the browser console, it looks like a couple of components failed to load, as well. Let us know if you start seeing this error regularly, but if it's only once in a while, I think we can say that it's a normal network error.

**Comment by dbemke** [comment]
**Tested with success!**
