### ISSUE TITLE
Migrate entity-creating forms to 2024.1.0 entities spec

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#757]
This is a follow-up issue to #692. The goal of this issue is to migrate additional forms to an entities spec version of 2024.1.0. #692 migrated entity-updating forms that had an entities spec version of 2023.1.0. This issue is to migrate all other forms that change entities and specify an old entities spec version. That includes forms with an entities spec version of 2023.1.0 that only create entities (not update them), as well as forms with an entities spec version that predates 2023.1.0. For these additional forms, the only change that is needed is to the entities spec version. Branch-related attributes like `branchId` do not need to be added to these forms.

**Comment by srujner** [comment]
**Tested with Success!**
