### ISSUE TITLE
Reject creating property with name that case-insensitively matches an existing property

### ISSUE THREAD

**Issue by lognaturel** [getodk/central#769]
It's currently possible to create multiple properties that only differ by case: https://staging.getodk.cloud/#/projects/103/entity-lists/cacti

It's unlikely that users actually want such duplicate names. I think it's pretty easy to accidentally end up in this state if multiple form definitions update the same properties by introducing a case typo in one of them.

I believe we already reject Entity List names that are case-insensitive duplicates. I think we should do the same for property names.

**Comment by sadiqkhoja** [comment]
Need help with the copy of the error message, specially the list of duplicate properties, does following look okay? Each bullet point shows name of the property provided in the uploaded Form definition and in the bracket name of the existing property is shown:`<provided in the Form> (existing: <current in the Entity list>)`

![image](https://github.com/user-attachments/assets/ae0609d7-dffc-4115-a0ff-61248fb4f668)

**Comment by lognaturel** [comment]
How about

> This form attempts to create new Entity properties that match with existing ones except for capitalization:
> * Geometry (existing: geometry)
> * Species (existing: species)

**Comment by dbemke** [comment]
We finished testing. The only thing we're not sure about is the message in case when I try to add a new form which contains 2 duplicate entities. When I upload a new version of an already publish form there's information :"This form attempts to create new Entity properties that match with existing ones except for capitalization". So when a user tries to add a new form with duplicate entities there's a bit less information what to correct in the form - is it expected?
![Image](https://github.com/user-attachments/assets/df71e9b2-fdd3-4ce5-96a2-c6c5b115c86e)

**Comment by sadiqkhoja** [comment]
This is an existing error message but we can certainly add list of duplicated properties here as well.

**Comment by dbemke** [comment]
**Tested with success!** (issues were filed separately)

**Comment by WKobus** [comment]
**Tested with success!**
