### ISSUE TITLE
Improve error message when a soft-deleted form gets re-submitted

### ISSUE THREAD

**Issue by dbemke** [getodk/central#794]
#### Action to take
In https://github.com/getodk/central/issues/794#issuecomment-2494706271, we agreed to add an improved error message in Central for this case.

If Central receives a submission with an instanceID it recognizes as being soft-deleted, it should return a new problem and the error text:

> This submission has been deleted. You may not resubmit it.

#### Problem description
Re-submitting a submission which was deleted
#### URL of the page
https://staging.getodk.cloud/
#### Steps to reproduce the problem
1. In Collect send a submission of a form.
2. In Central delete the submission.
3. In Collect go to "Ready to send- Change View- Show Sent and UnsentForms”.
4. Select the sent submission and tap "Send Selected”
#### Screenshot
![sendSentDeletedSub](https://github.com/user-attachments/assets/c1db8f98-22ca-4e41-988c-7396a0c3a35f)

#### Expected behavior
From the thread in collect slack- Ln :
"When re-submitting a deleted submission, here are some reasonable outcomes I can think of:
- Central accepts the submission but doesn’t do anything with it (behavior when a submission isn’t deleted)
- Central accepts the submission and un-deletes it
- Central rejects the submission with an error saying the submission has been received and then deleted (similar to the second case but with a better error message)"

#### Central version shown in version.txt
https://staging.getodk.cloud/
versions:
2e5c4f7de60c6db39c3205320cedba95d49a9aa3 (v2024.2.1-3-g2e5c4f7)
+4a5a9ff81efff48a1500214d9c826b590c9ddaed client (v2024.2.1-16-g4a5a9ff8)
+746ff058d32d968f13cf4e7b0a48b81f88fb21df server (v2024.2.0-79-g746ff058)

**Comment by matthew-white** [comment]
Not that this was suggested, but I don't think we should allow there to be multiple submissions with the same instance ID, even if one is deleted. Otherwise, we'd have to expose the numeric `submissionId` for undeleting submissions, similar to how we have to expose `formId` for undeleting forms. That's because `xmlFormId` doesn't necessarily uniquely identify forms when you include deleted forms.

> Central rejects the submission with an error saying the submission has been received and then deleted (similar to the second case but with a better error message)

I think this would be the easiest thing to do. I also like that it's explicit about what the situation is. Could we run with this, then see how often this situation comes up?

**Comment by lognaturel** [comment]
I think it would be reasonable for Central to have a special message like "This submission was previously received and deleted." If we want to be more precise, we could go with something like "The ID of this submission matches the ID of a deleted submission." but I don't think that's as helpful for users.

Alternatively, we'd want to have a special code that Collect can detect that is just about this deleted match case.

**Comment by lognaturel** [comment]
> that's a specific Problem with a more informative error message (a 409.6). I think we should do something similar in this case.

Perfect, let's do that.

>  I don't think we send it over OpenRosa. From what I can tell, it'd be easy to do so though.

I think we should to give clients the option of having their own localized and potentially more detailed error messages. That will probably be a whole separate project, though, and we don't have to do it now.

**Comment by matthew-white** [comment]
> I think we should to give clients the option of having their own localized and potentially more detailed error messages.

I personally feel like we would benefit from having server-side localization at some point. Both error messages and emails would benefit from being localized. If Backend did more localization, then Frontend would have less of that homework (#489). More to the current point, clients like Collect could tell Backend what locale they prefer for error messages via the `Accept-Language` header.

> That will probably be a whole separate project, though, and we don't have to do it now.

Sounds good. :+1: Seeing localized error messages in the client definitely sound like a nice thing at some point.

**Comment by lognaturel** [comment]
Proposed error text: "This submission has been deleted. You may not resubmit it."

**Comment by sadiqkhoja** [comment]
@lognaturel I am assuming this is only needed for OpenRosa endpoint, right? For REST endpoint we don't allow resubmissions.

**Comment by lognaturel** [comment]
Sounds right!

**Comment by srujner** [comment]
**Tested with Success!**
