### ISSUE TITLE
Accept submissions belonging to unknown form versions

### ISSUE THREAD

**Issue by ggalmazor** [getodk/central#80]
We have already discussed this before, and now that Briefcase supports Central, we thought better to document this as an issue and start discussing options.

The scenario:
- A user has gone through many versions of a form and has submissions belonging to all versions
- The user wants to use Briefcase to push the form and its submissions to a Central server
  - Briefcase stores the blank form belonging to the last existing version of it
  - Briefcase has submissions belonging to all versions that have existed
- The user hasn't sent anything to Central yet.

The problem:
- Briefcase has no record of previous versions of the form
- Briefcase is able to push the blank form
- Briefcase is able to push the submissions matching the version of the blank form
- Other submissions are rejected

**Comment by ggalmazor** [comment]
So, one solution would be to have Briefcase store different versions of a blank form, but then, users still could miss a version and not all their submissions would reach Central.

**Comment by issa-tseng** [comment]
i just taught central how to keep track of multiple versions of a form, though there is no exposed way to access this facility yet, as i’m not yet certain how best to build a user experience around it. so at least, at some point if briefcase _does_ remember past versions of a form, it can send them all and central will shuffle submissions to the appropriate spots.

but as you point out, if they don’t have some past version of the schema, central will still reject. i guess my question is, lacking a schema i can’t do anything sensible with the submission at all, so what is the utility of having central store it? it doesn’t really have any bulk export functionality other than OData or CSV, and both of those paths require a schema.

**Comment by ggalmazor** [comment]
> ...  central will shuffle submissions to the appropriate spots.
awesome!

> ... lacking a schema i can’t do anything sensible with the submission at all ...

Briefcase deals with this by assuming that all submissions follow the schema of the form it has in storage, regardless of any version mismatch.

Missing fields in the submission are exported as blank values, and extra fields are ignored (not exported).

This kinda works well (no complains so far)

**Comment by issa-tseng** [comment]
yeah... i'm rather uncomfortable with that approach. my hope and goal with form versioning is that some kind of principled data migration approach can be devised that understands exactly how to transform submission data forward through each version.

**Comment by issa-tseng** [comment]
i think one way i can soften this is to optionally (opt-in) create implicit formdef records for versions it does not recognize, and store the submissions, but not perform ops on those submissions unless the formdef is completed with a schema.

**Comment by lognaturel** [comment]
This has been addressed in Briefcase by https://github.com/getodk/briefcase/pull/872. We send the same form definition schema with injected version values matching all of the versions there are submissions for. This is not perfect but for the time being, Central only uses the latest schema to do anything with so it's good enough. We also describe the behavior to the user and suggest that if they have all form definition versions, they could manually upload those first.

I don't think there's a generic need here that still needs addressing so closing.
