### ISSUE TITLE
After Undelete all submissions, a button is left with “0 deleted Submissions”

### ISSUE THREAD

**Issue by srujner** [getodk/central#806]
#### Problem description
Issue found during testing: https://github.com/getodk/central/issues/709 
After Undelete all submissions, a button is left with “0 deleted Submissions”

#### URL of the page
https://staging.getodk.cloud/#/projects/124/forms/rank_fruit/submissions?deleted=true

#### Steps to reproduce the problem
1. Navigate to the submission tab of any project
2. Create a submission and delete it
3. Click on the Deleted Submissions button
4. Undelete Submission
5. The button with "0 deleted Submissions" is still visible

#### Screenshot
![Screenshot(129)](https://github.com/user-attachments/assets/b8570346-3fd6-4eaa-bf7f-9c41ecad6524)

#### Expected behavior
Not sure what should be expected here, maybe after restoring the last submission user should be automatically moved to the submission list

#### Central version shown in version.txt
51a3e10fdf188473ce38b24313962c674188c9ff (v2024.2.1-4-g51a3e10)
+bb2b2325c5fde4e1325e0d0fcec9c3db6a58cfd7 client (v2024.2.1-35-gbb2b2325)
+57c4da581a21928eb21fef8097f72870af6e4d4d server (v2024.2.0-83-g57c4da58)

#### Browser version
Firefox 132.0 (64-bit)

**Comment by lognaturel** [comment]
> maybe after restoring the last submission user should be automatically moved to the submission list

That would be slightly nicer! We're not going to prioritize it for now so I'll close but we can keep an eye on whether users find it confusing and reopen.
