### ISSUE TITLE
Survey ID not found Loading Error

### ISSUE THREAD

**Issue by srujner** [getodk/central#807]
**Problem description**

Last week I was testing submission deletion in this project and everything worked fine. 
Today after couple of days of not touching this project I wanted to send a single submission and I get an error in Enketo that: 
"Survey with this ID not found". It appears for all submissions in that project, but also in other older projects. 
In the new created project everything looks ok. 
I'm not sure if this is a Central issue or Enketo.

**URL of the page**
https://staging.getodk.cloud/#/projects/124

Steps to reproduce the problem
1. Navigate to the submission tab of any form
2. Click on the New button 
3. The error in Enketo will occur 

**Screenshot**
![Screenshot(176)](https://github.com/user-attachments/assets/d87625b2-bf5c-42f5-bee2-12739e632ccf)

**Expected behavior**

There should be no error when trying to create a submission. 

**Central version shown in version.txt**
versions:
51a3e10fdf188473ce38b24313962c674188c9ff (v2024.2.1-4-g51a3e10)
+bb2b2325c5fde4e1325e0d0fcec9c3db6a58cfd7 client (v2024.2.1-35-gbb2b2325)
+57c4da581a21928eb21fef8097f72870af6e4d4d server (v2024.2.0-83-g57c4da58)

**Browser version**
Firefox 132.0 (64-bit)

**Comment by lognaturel** [comment]
This is an issue specific to that server. Will look into it!
