### ISSUE TITLE
Editing an entity created by update for and sending registration form afterwards

### ISSUE THREAD

**Issue by dbemke** [getodk/central#810]
#### Problem description
If a user edits an entity created by update form,sending registration form afterwards results in "Problem processing Entity Query returns an unexpected result." (in the registration form submission detail page). I noticed it in one form - I haven't been able to reproduce it with a different form.
#### URL of the page
e.g. https://staging.getodk.cloud/#/projects/101/app-users
#### Steps to reproduce the problem
1. In Collect add user "children” https://staging.getodk.cloud/#/projects/101/app-users
2. Set auto send to "off”.
3. Fill and finalize child-only registration without age const form.
4. Go to Child update form an update the created entity, finalize the form.
5. Go to "ready to send” and select the update form and send it.
6. Wait for force-processing the submission/entity in the backlog.
7.  When the entity is created in Central, go to the entity detail page and edit the entity.
![editedUptCret](https://github.com/user-attachments/assets/82ff5ec4-9348-466e-94f0-a9787c335f8a)

8. Send the registration form
9. Go to the submission detail  page of the registration form

#### Screenshot
![registAfterEditUpt](https://github.com/user-attachments/assets/a46296cd-d485-4888-979e-2446016b3d84)

#### Expected behavior
The registration form should be able to modify the entity
#### Central version shown in version.txt

https://staging.getodk.cloud/
versions:
51a3e10fdf188473ce38b24313962c674188c9ff (v2024.2.1-4-g51a3e10)
+bb2b2325c5fde4e1325e0d0fcec9c3db6a58cfd7 client (v2024.2.1-35-gbb2b2325)
+57c4da581a21928eb21fef8097f72870af6e4d4d server (v2024.2.0-83-g57c4da58)

**Comment by matthew-white** [comment]
@ktuite, this might be a good one for you to look into if you have time.

**Comment by dbemke** [comment]
**Tested with success!**

**Comment by WKobus** [comment]
**Tested with success!**
