### ISSUE TITLE
Update buttons above Draft test Submissions

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#833]
See the story in the [release criteria](https://docs.google.com/document/d/1sjAB68yy17Aw0gu5UYtAuadlg8mftsEJmVJD3el54QI/edit?tab=t.0#heading=h.9b1l08epoku6).

**Comment by matthew-white** [comment]
I'm going to go ahead and close this out now that getodk/central-frontend#1098 is merged and the refresh button is next to the download button on the draft testing page. There are still a couple of very small to-dos above, but I don't think that should stop @getodk/testers from starting to take a look.

**Comment by srujner** [comment]
Tested with Success
