### ISSUE TITLE
Handle long project (or form) name in breadcrumbs

### ISSUE THREAD

**Issue by ktuite** [getodk/central#834]
> Long Project name can break the breadcrumb:
![Screenshot(204)](https://github.com/user-attachments/assets/a39fcc53-befa-4b77-ad37-6c2c6add4791)

_Originally posted by @srujner in https://github.com/getodk/central/issues/674#issuecomment-2519864542_

**Comment by matthew-white** [comment]
Instead of doing something super dynamic, could we just add a reasonable `max-width` + tooltip to `.breadcrumb-item`? The user name in the navbar dropdown on the right maxes out at 275px, so maybe that'd be a good width.

**Comment by srujner** [comment]
Tested with Success!
